# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `arbre` gem.
# Please instead update this file by running `bin/tapioca gem arbre`.


# pkg:gem/arbre#lib/arbre.rb:6
module Arbre; end

# pkg:gem/arbre#lib/arbre/component.rb:3
class Arbre::Component < ::Arbre::HTML::Div
  # pkg:gem/arbre#lib/arbre/component.rb:10
  def initialize(*_arg0); end

  # By default components render a div
  #
  # pkg:gem/arbre#lib/arbre/component.rb:6
  def tag_name; end

  protected

  # By default, add a css class named after the ruby class
  #
  # pkg:gem/arbre#lib/arbre/component.rb:18
  def default_class_name; end
end

# The Arbre::Context class is the frontend for using Arbre.
#
# The simplest example possible:
#
#     html = Arbre::Context.new do
#       h1 "Hello World"
#     end
#
#     html.to_s #=> "<h1>Hello World</h1>"
#
# The contents of the block are instance eval'd within the Context
# object. This means that you lose context to the outside world from
# within the block. To pass local variables into the Context, use the
# assigns param.
#
#     html = Arbre::Context.new({one: 1}) do
#       h1 "Your number #{one}"
#     end
#
#     html.to_s #=> "Your number 1"
#
# pkg:gem/arbre#lib/arbre/context.rb:28
class Arbre::Context < ::Arbre::Element
  # Initialize a new Arbre::Context
  #
  # @param [Hash] assigns A hash of objecs that you would like to be
  #                       available as local variables within the Context
  #
  # @param [Object] helpers An object that has methods on it which will become
  #                         instance methods within the context.
  #
  # @yield [] The block that will get instance eval'd in the context
  #
  # pkg:gem/arbre#lib/arbre/context.rb:39
  def initialize(assigns = T.unsafe(nil), helpers = T.unsafe(nil), &block); end

  # pkg:gem/arbre#lib/arbre/context.rb:50
  def arbre_context; end

  # pkg:gem/arbre#lib/arbre/context.rb:54
  def assigns; end

  # pkg:gem/arbre#lib/arbre/context.rb:67
  def bytesize; end

  # pkg:gem/arbre#lib/arbre/context.rb:87
  def current_arbre_element; end

  # pkg:gem/arbre#lib/arbre/context.rb:58
  def helpers; end

  # pkg:gem/arbre#lib/arbre/context.rb:62
  def indent_level; end

  # pkg:gem/arbre#lib/arbre/context.rb:70
  def length; end

  # pkg:gem/arbre#lib/arbre/context.rb:79
  def method_missing(method, *args, **_arg2, &block); end

  # pkg:gem/arbre#lib/arbre/context.rb:91
  def with_current_arbre_element(tag); end

  # pkg:gem/arbre#lib/arbre/context.rb:97
  def within(tag); end

  private

  # Caches the rendered HTML so that we don't re-render just to
  # get the content length or to delegate a method to the HTML
  #
  # pkg:gem/arbre#lib/arbre/context.rb:104
  def cached_html; end

  # pkg:gem/arbre#lib/arbre/context.rb:72
  def respond_to_missing?(method, include_all); end
end

# pkg:gem/arbre#lib/arbre/element/builder_methods.rb:3
class Arbre::Element
  include ::Arbre::Element::BuilderMethods
  include ::Arbre::Rails::Rendering
  extend ::Arbre::Element::BuilderMethods::ClassMethods

  # pkg:gem/arbre#lib/arbre/element.rb:15
  def initialize(arbre_context = T.unsafe(nil)); end

  # pkg:gem/arbre#lib/arbre/element.rb:148
  def +(element); end

  # pkg:gem/arbre#lib/arbre/element.rb:66
  def <<(child); end

  # pkg:gem/arbre#lib/arbre/element.rb:38
  def add_child(child); end

  # pkg:gem/arbre#lib/arbre/element.rb:82
  def ancestors; end

  # pkg:gem/arbre#lib/arbre/element.rb:13
  def arbre_context; end

  # pkg:gem/arbre#lib/arbre/element.rb:21
  def assigns; end

  # pkg:gem/arbre#lib/arbre/element.rb:33
  def build(*args, &block); end

  # pkg:gem/arbre#lib/arbre/element.rb:13
  def children; end

  # pkg:gem/arbre#lib/arbre/element.rb:70
  def children?; end

  # pkg:gem/arbre#lib/arbre/element.rb:120
  def content; end

  # pkg:gem/arbre#lib/arbre/element.rb:95
  def content=(contents); end

  # pkg:gem/arbre#lib/arbre/element.rb:132
  def each(&block); end

  # pkg:gem/arbre#lib/arbre/element.rb:118
  def find_by_class(class_name); end

  # pkg:gem/arbre#lib/arbre/element.rb:108
  def find_by_tag(tag_name); end

  # TODO: Shouldn't grab whole tree
  #
  # pkg:gem/arbre#lib/arbre/element.rb:91
  def find_first_ancestor(type); end

  # pkg:gem/arbre#lib/arbre/element.rb:110
  def get_elements_by_class_name(class_name); end

  # pkg:gem/arbre#lib/arbre/element.rb:100
  def get_elements_by_tag_name(tag_name); end

  # pkg:gem/arbre#lib/arbre/element.rb:25
  def helpers; end

  # pkg:gem/arbre#lib/arbre/element.rb:124
  def html_safe; end

  # pkg:gem/arbre#lib/arbre/element.rb:128
  def indent_level; end

  # pkg:gem/arbre#lib/arbre/element.rb:136
  def inspect; end

  # pkg:gem/arbre#lib/arbre/element.rb:12
  def parent; end

  # pkg:gem/arbre#lib/arbre/element.rb:74
  def parent=(parent); end

  # pkg:gem/arbre#lib/arbre/element.rb:78
  def parent?; end

  # pkg:gem/arbre#lib/arbre/element.rb:61
  def remove_child(child); end

  # pkg:gem/arbre#lib/arbre/element.rb:29
  def tag_name; end

  # pkg:gem/arbre#lib/arbre/element.rb:160
  def to_a; end

  # pkg:gem/arbre#lib/arbre/element.rb:157
  def to_ary; end

  # pkg:gem/arbre#lib/arbre/element.rb:144
  def to_s; end

  # pkg:gem/arbre#lib/arbre/element.rb:140
  def to_str; end

  private

  # Resets the Elements children
  #
  # pkg:gem/arbre#lib/arbre/element.rb:165
  def clear_children!; end

  # pkg:gem/arbre#lib/arbre/element.rb:177
  def method_missing(name, *args, **_arg2, &block); end
end

# pkg:gem/arbre#lib/arbre/element/builder_methods.rb:5
module Arbre::Element::BuilderMethods
  mixes_in_class_methods ::Arbre::Element::BuilderMethods::ClassMethods

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def a(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def abbr(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def address(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def area(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def article(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def aside(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def audio(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def b(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def base(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def bdo(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def blockquote(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def body(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def br(*args, &block); end

  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:23
  def build_tag(klass, *args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def button(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def canvas(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def caption(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def cite(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def code(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def col(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def colgroup(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def command(*args, &block); end

  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:45
  def current_arbre_element; end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def datalist(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def dd(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def del(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def details(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def dfn(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def div(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def dl(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def dt(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def em(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def embed(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def fieldset(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def figcaption(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def figure(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def footer(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def form(*args, &block); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:45
  def form_for(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def h1(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def h2(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def h3(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def h4(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def h5(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def h6(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def head(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def header(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def hgroup(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def hr(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def html(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def i(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def iframe(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def img(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def input(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def ins(*args, &block); end

  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:39
  def insert_tag(klass, *args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def kbd(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def keygen(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def label(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def legend(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def li(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def link(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def main(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def map(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def mark(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def menu(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def menuitem(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def meta(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def meter(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def nav(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def noscript(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def object(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def ol(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def optgroup(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def option(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def output(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:28
  def para(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def param(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def pre(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def progress(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def q(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def s(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def samp(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def script(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def section(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def select(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def small(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def source(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def span(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def strong(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def style(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def sub(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def summary(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def sup(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def svg(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def table(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def tbody(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def td(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/text_node.rb:9
  def text_node(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def textarea(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def tfoot(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def th(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def thead(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def time(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def title(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def tr(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def track(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def ul(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def var(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def video(*args, &block); end

  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
  def wbr(*args, &block); end

  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:49
  def with_current_arbre_element(tag, &block); end

  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:52
  def within(tag, &block); end

  private

  # Appends the value to the current DOM element if there are no
  # existing DOM Children and it responds to #to_s
  #
  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:58
  def append_return_block(tag); end

  # Returns true if the object should be converted into a text node
  # and appended into the DOM.
  #
  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:68
  def appendable_tag?(tag); end

  class << self
    # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:7
    def included(klass); end
  end
end

# pkg:gem/arbre#lib/arbre/element/builder_methods.rb:11
module Arbre::Element::BuilderMethods::ClassMethods
  # pkg:gem/arbre#lib/arbre/element/builder_methods.rb:13
  def builder_method(method_name); end
end

# pkg:gem/arbre#lib/arbre/element/proxy.rb:4
class Arbre::Element::Proxy < ::BasicObject
  # pkg:gem/arbre#lib/arbre/element/proxy.rb:8
  def initialize(element); end

  # pkg:gem/arbre#lib/arbre/element/proxy.rb:20
  def method_missing(method, *args, &block); end

  # pkg:gem/arbre#lib/arbre/element/proxy.rb:12
  def respond_to?(method, include_all = T.unsafe(nil)); end
end

# Stores a collection of Element objects
#
# pkg:gem/arbre#lib/arbre/element_collection.rb:5
class Arbre::ElementCollection < ::Array
  # pkg:gem/arbre#lib/arbre/element_collection.rb:15
  def &(other); end

  # pkg:gem/arbre#lib/arbre/element_collection.rb:7
  def +(other); end

  # pkg:gem/arbre#lib/arbre/element_collection.rb:11
  def -(other); end

  # pkg:gem/arbre#lib/arbre/element_collection.rb:19
  def to_s; end
end

# pkg:gem/arbre#lib/arbre/html/attributes.rb:3
module Arbre::HTML; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::A < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:5
Arbre::HTML::AUTO_BUILD_ELEMENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Abbr < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Address < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Area < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Article < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Aside < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/attributes.rb:5
class Arbre::HTML::Attributes < ::Hash
  # pkg:gem/arbre#lib/arbre/html/attributes.rb:14
  def any?; end

  # pkg:gem/arbre#lib/arbre/html/attributes.rb:7
  def to_s; end

  protected

  # pkg:gem/arbre#lib/arbre/html/attributes.rb:20
  def flatten_hash(hash = T.unsafe(nil), old_path = T.unsafe(nil), accumulator = T.unsafe(nil)); end

  # pkg:gem/arbre#lib/arbre/html/attributes.rb:36
  def html_escape(s); end

  # pkg:gem/arbre#lib/arbre/html/attributes.rb:32
  def value_empty?(value); end
end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Audio < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::B < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Base < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Bdo < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Blockquote < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Body < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Br < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Button < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Canvas < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Caption < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Cite < ::Arbre::HTML::Tag; end

# Holds a set of classes
#
# pkg:gem/arbre#lib/arbre/html/class_list.rb:8
class Arbre::HTML::ClassList < ::Set
  include ::Set::SubclassCompatible
  extend ::Set::SubclassCompatible::ClassMethods

  # pkg:gem/arbre#lib/arbre/html/class_list.rb:20
  def <<(class_names); end

  # pkg:gem/arbre#lib/arbre/html/class_list.rb:14
  def add(class_names); end

  # pkg:gem/arbre#lib/arbre/html/class_list.rb:22
  def to_s; end

  class << self
    # pkg:gem/arbre#lib/arbre/html/class_list.rb:10
    def build_from_string(class_names); end
  end
end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Code < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Col < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Colgroup < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Command < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Datalist < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Dd < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Del < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Details < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Dfn < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Div < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Dl < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/document.rb:5
class Arbre::HTML::Document < ::Arbre::HTML::Tag
  # pkg:gem/arbre#lib/arbre/html/document.rb:7
  def build(*args); end

  # pkg:gem/arbre#lib/arbre/html/document.rb:21
  def doctype; end

  # pkg:gem/arbre#lib/arbre/html/document.rb:13
  def document; end

  # pkg:gem/arbre#lib/arbre/html/document.rb:17
  def tag_name; end

  # pkg:gem/arbre#lib/arbre/html/document.rb:25
  def to_s; end

  protected

  # pkg:gem/arbre#lib/arbre/html/document.rb:37
  def build_body; end

  # pkg:gem/arbre#lib/arbre/html/document.rb:31
  def build_head; end
end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Dt < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Em < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Embed < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Fieldset < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Figcaption < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Figure < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Footer < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Form < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::H1 < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::H2 < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::H3 < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::H4 < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::H5 < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::H6 < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:17
Arbre::HTML::HTML5_ELEMENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Head < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Header < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Hgroup < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Hr < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Html < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::I < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Iframe < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Img < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Input < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Ins < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Kbd < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Keygen < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Label < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Legend < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Li < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Link < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Main < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Map < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Mark < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Menu < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Menuitem < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Meta < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Meter < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Nav < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Noscript < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Object < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Ol < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Optgroup < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Option < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Output < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:27
class Arbre::HTML::P < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Param < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Pre < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Progress < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Q < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::S < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Samp < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Script < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Section < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Select < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Small < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Source < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Span < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Strong < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Style < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Sub < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Summary < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Sup < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Svg < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Table < ::Arbre::HTML::Tag
  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:32
  def initialize(*_arg0); end

  protected

  # Set some good defaults for tables
  #
  # pkg:gem/arbre#lib/arbre/html/html5_elements.rb:40
  def set_table_tag_defaults; end
end

# pkg:gem/arbre#lib/arbre/html/tag.rb:7
class Arbre::HTML::Tag < ::Arbre::Element
  # pkg:gem/arbre#lib/arbre/html/tag.rb:14
  def initialize(*_arg0); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:74
  def add_class(class_names); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:49
  def attr(name); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:8
  def attributes; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:19
  def build(*args); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:87
  def class_list; end

  # Returns a string of classes
  #
  # pkg:gem/arbre#lib/arbre/html/tag.rb:83
  def class_names; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:34
  def extract_arguments(args); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:46
  def get_attribute(name); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:51
  def has_attribute?(name); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:59
  def id; end

  # Generates and id for the object if it doesn't exist already
  #
  # pkg:gem/arbre#lib/arbre/html/tag.rb:64
  def id!; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:70
  def id=(id); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:55
  def remove_attribute(name); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:78
  def remove_class(class_names); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:42
  def set_attribute(name, value); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:100
  def to_s; end

  private

  # pkg:gem/arbre#lib/arbre/html/tag.rb:152
  def attributes_html; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:148
  def child_is_text?; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:110
  def closing_tag; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:184
  def default_id_for_prefix; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:164
  def dom_class_name_for(record); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:172
  def dom_id_for(record); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:116
  def indent(open_tag, child_content, close_tag); end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:144
  def no_child?; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:106
  def opening_tag; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:140
  def self_closing_tag?; end

  # pkg:gem/arbre#lib/arbre/html/tag.rb:156
  def set_for_attribute(record); end
end

# pkg:gem/arbre#lib/arbre/html/tag.rb:114
Arbre::HTML::Tag::INDENT_SIZE = T.let(T.unsafe(nil), Integer)

# See: http://www.w3.org/html/wg/drafts/html/master/syntax.html#void-elements
#
# pkg:gem/arbre#lib/arbre/html/tag.rb:11
Arbre::HTML::Tag::SELF_CLOSING_ELEMENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Tbody < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Td < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/text_node.rb:7
class Arbre::HTML::TextNode < ::Arbre::Element
  # pkg:gem/arbre#lib/arbre/html/text_node.rb:18
  def add_child(*args); end

  # pkg:gem/arbre#lib/arbre/html/text_node.rb:22
  def build(string); end

  # pkg:gem/arbre#lib/arbre/html/text_node.rb:26
  def class_list; end

  # pkg:gem/arbre#lib/arbre/html/text_node.rb:30
  def tag_name; end

  # pkg:gem/arbre#lib/arbre/html/text_node.rb:34
  def to_s; end

  class << self
    # Builds a text node from a string
    #
    # pkg:gem/arbre#lib/arbre/html/text_node.rb:12
    def from_string(string); end
  end
end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Textarea < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Tfoot < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Th < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Thead < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Time < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Title < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Tr < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Track < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Ul < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Var < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Video < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/html/html5_elements.rb:20
class Arbre::HTML::Wbr < ::Arbre::HTML::Tag; end

# pkg:gem/arbre#lib/arbre/rails/template_handler.rb:3
module Arbre::Rails; end

# pkg:gem/arbre#lib/arbre/rails/forms.rb:4
module Arbre::Rails::Forms; end

# pkg:gem/arbre#lib/arbre/rails/forms.rb:76
class Arbre::Rails::Forms::FieldsForProxy < ::Arbre::Rails::Forms::FormBuilderProxy
  # pkg:gem/arbre#lib/arbre/rails/forms.rb:78
  def build(form_builder, *args, &block); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:86
  def to_s; end
end

# pkg:gem/arbre#lib/arbre/rails/forms.rb:6
class Arbre::Rails::Forms::FormBuilderProxy < ::Arbre::Component
  # pkg:gem/arbre#lib/arbre/rails/forms.rb:7
  def form_builder; end

  # Since label and select are Arbre Elements already, we must
  # override it here instead of letting method_missing
  # deal with it
  #
  # pkg:gem/arbre#lib/arbre/rails/forms.rb:12
  def label(*args); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:16
  def select(*args); end

  private

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:34
  def method_missing(method, *args, **_arg2, &block); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:30
  def proxy_call_to_form(method, *args, &block); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:20
  def respond_to_missing?(method, include_all); end
end

# pkg:gem/arbre#lib/arbre/rails/forms.rb:44
class Arbre::Rails::Forms::FormForProxy < ::Arbre::Rails::Forms::FormBuilderProxy
  # pkg:gem/arbre#lib/arbre/rails/forms.rb:47
  def build(resource, form_options = T.unsafe(nil), &block); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:70
  def closing_tag; end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:56
  def fields_for(*args, &block); end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:66
  def opening_tag; end

  # pkg:gem/arbre#lib/arbre/rails/forms.rb:60
  def split_string_on(string, match); end
end

# pkg:gem/arbre#lib/arbre/rails/rendering.rb:4
module Arbre::Rails::Rendering
  # pkg:gem/arbre#lib/arbre/rails/rendering.rb:6
  def render(*args); end
end

# pkg:gem/arbre#lib/arbre/rails/template_handler.rb:4
class Arbre::Rails::TemplateHandler
  # pkg:gem/arbre#lib/arbre/rails/template_handler.rb:5
  def call(template, source = T.unsafe(nil)); end
end

# pkg:gem/arbre#lib/arbre/railtie.rb:10
class Arbre::Railtie < ::Rails::Railtie; end
