# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `icalendar` gem.
# Please instead update this file by running `bin/tapioca gem icalendar`.


# This module contains mappings from Windows timezone identifiers to Olson timezone identifiers.
#
# The data is taken from the unicode consortium [0], the proposal and rationale
# for this mapping is also available at the unicode consortium [1].
#
# [0] https://www.unicode.org/cldr/cldr-aux/charts/29/supplemental/zone_tzid.html
# [1] https://cldr.unicode.org/development/development-process/design-proposals/extended-windows-olson-zid-mapping
#
# pkg:gem/icalendar#lib/icalendar/logger.rb:6
module Icalendar
  class << self
    # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:67
    def DowncasedHash(base); end

    # pkg:gem/icalendar#lib/icalendar.rb:9
    def logger; end

    # pkg:gem/icalendar#lib/icalendar.rb:13
    def logger=(logger); end

    # pkg:gem/icalendar#lib/icalendar.rb:17
    def parse(source, single = T.unsafe(nil)); end
  end
end

# pkg:gem/icalendar#lib/icalendar/alarm.rb:5
class Icalendar::Alarm < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/alarm.rb:25
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:23
  def acknowledged; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:23
  def acknowledged=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:7
  def action; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:7
  def action=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:19
  def append_attach(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:13
  def append_attendee(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:19
  def attach; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:19
  def attach=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:13
  def attendee; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:13
  def attendee=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:9
  def description; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:9
  def description=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:16
  def duration; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:16
  def duration=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:17
  def repeat; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:17
  def repeat=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:11
  def summary; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:11
  def summary=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:8
  def trigger; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:8
  def trigger=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:22
  def uid; end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:22
  def uid=(value); end

  # pkg:gem/icalendar#lib/icalendar/alarm.rb:30
  def valid?(strict = T.unsafe(nil)); end
end

# pkg:gem/icalendar#lib/icalendar/calendar.rb:5
class Icalendar::Calendar < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/calendar.rb:27
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:49
  def add; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:22
  def add_event(c); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:25
  def add_freebusy(c); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:24
  def add_journal(c); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:21
  def add_timezone(c); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:23
  def add_todo(c); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:15
  def append_categories(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:11
  def append_description(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:19
  def append_image(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:10
  def append_ip_name(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:8
  def calscale; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:8
  def calscale=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:54
  def cancel; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:15
  def categories; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:15
  def categories=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:18
  def color; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:18
  def color=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:64
  def counter; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:69
  def decline_counter; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:11
  def description; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:11
  def description=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:22
  def event(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:22
  def events; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:22
  def find_event(id); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:25
  def find_freebusy(id); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:24
  def find_journal(id); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:21
  def find_timezone(id); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:23
  def find_todo(id); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:25
  def freebusy(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:25
  def freebusys; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:22
  def has_event?; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:25
  def has_freebusy?; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:24
  def has_journal?; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:21
  def has_timezone?; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:23
  def has_todo?; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:19
  def image; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:19
  def image=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:9
  def ip_method; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:9
  def ip_method=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:10
  def ip_name; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:10
  def ip_name=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:24
  def journal(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:24
  def journals; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:13
  def last_modified; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:13
  def last_modified=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:7
  def prodid; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:7
  def prodid=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:34
  def publish; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:59
  def refresh; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:16
  def refresh_interval; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:16
  def refresh_interval=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:44
  def reply; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:39
  def request; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:17
  def source; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:17
  def source=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:21
  def timezone(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:21
  def timezones; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:23
  def todo(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:23
  def todos; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:12
  def uid; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:12
  def uid=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:14
  def url; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:14
  def url=(value); end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:6
  def version; end

  # pkg:gem/icalendar#lib/icalendar/calendar.rb:6
  def version=(value); end
end

# pkg:gem/icalendar#lib/icalendar/component.rb:7
class Icalendar::Component
  include ::Icalendar::HasProperties
  include ::Icalendar::HasComponents
  extend ::Icalendar::HasProperties::ClassMethods
  extend ::Icalendar::HasComponents::ClassMethods

  # pkg:gem/icalendar#lib/icalendar/component.rb:22
  def initialize(name, ical_name = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/component.rb:9
  def custom_components; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:8
  def custom_properties; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:12
  def ical_name; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:11
  def name; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:28
  def new_uid; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:13
  def parent; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:13
  def parent=(_arg0); end

  # pkg:gem/icalendar#lib/icalendar/component.rb:32
  def to_ical; end

  private

  # pkg:gem/icalendar#lib/icalendar/component.rb:101
  def ical_components; end

  # pkg:gem/icalendar#lib/icalendar/component.rb:66
  def ical_fold(long_line, indent = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/component.rb:60
  def ical_prop_name(prop_name); end

  # pkg:gem/icalendar#lib/icalendar/component.rb:43
  def ical_properties; end

  class << self
    # pkg:gem/icalendar#lib/icalendar/component.rb:15
    def parse(source); end

    private

    # pkg:gem/icalendar#lib/icalendar/component.rb:113
    def _parse(source); end
  end
end

# pkg:gem/icalendar#lib/icalendar/component.rb:64
Icalendar::Component::ICAL_FOLD_LONG_LINE_SCAN_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/component.rb:58
Icalendar::Component::ICAL_PROP_NAME_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:6
class Icalendar::DowncasedHash
  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:8
  def initialize(base); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:58
  def ==(other); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:19
  def [](key); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:15
  def []=(key, value); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:29
  def delete(key, &block); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:50
  def each(&block); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:46
  def empty?; end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:23
  def has_key?(key); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:26
  def include?(key); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:54
  def map(&block); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:27
  def member?(key); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:33
  def merge(*other_hashes); end

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:37
  def merge!(*other_hashes); end

  protected

  # pkg:gem/icalendar#lib/icalendar/downcased_hash.rb:64
  def obj; end
end

# pkg:gem/icalendar#lib/icalendar/event.rb:5
class Icalendar::Event < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/event.rb:48
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:46
  def add_alarm(c); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:46
  def alarm(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:46
  def alarms; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:33
  def append_attach(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:34
  def append_attendee(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:35
  def append_categories(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:36
  def append_comment(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:43
  def append_conference(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:37
  def append_contact(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:38
  def append_exdate(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:44
  def append_image(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:42
  def append_rdate(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:40
  def append_related_to(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:39
  def append_request_status(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:41
  def append_resources(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:32
  def append_rrule(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:33
  def attach; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:33
  def attach=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:34
  def attendee; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:34
  def attendee=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:35
  def categories; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:35
  def categories=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:17
  def color; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:17
  def color=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:36
  def comment; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:36
  def comment=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:43
  def conference; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:43
  def conference=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:37
  def contact; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:37
  def contact=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:18
  def created; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:18
  def created=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:19
  def description; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:19
  def description=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:12
  def dtend; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:12
  def dtend=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:6
  def dtstamp; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:6
  def dtstamp=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:9
  def dtstart; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:9
  def dtstart=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:13
  def duration; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:13
  def duration=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:38
  def exdate; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:38
  def exdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:20
  def geo; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:20
  def geo=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:46
  def has_alarm?; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:44
  def image; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:44
  def image=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:16
  def ip_class; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:16
  def ip_class=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:21
  def last_modified; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:21
  def last_modified=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:22
  def location; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:22
  def location=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:23
  def organizer; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:23
  def organizer=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:24
  def priority; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:24
  def priority=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:42
  def rdate; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:42
  def rdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:30
  def recurrence_id; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:30
  def recurrence_id=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:40
  def related_to; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:40
  def related_to=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:39
  def request_status; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:39
  def request_status=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:41
  def resources; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:41
  def resources=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:32
  def rrule; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:32
  def rrule=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:25
  def sequence; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:25
  def sequence=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:26
  def status; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:26
  def status=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:27
  def summary; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:27
  def summary=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:28
  def transp; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:28
  def transp=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:7
  def uid; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:7
  def uid=(value); end

  # pkg:gem/icalendar#lib/icalendar/event.rb:29
  def url; end

  # pkg:gem/icalendar#lib/icalendar/event.rb:29
  def url=(value); end
end

# pkg:gem/icalendar#lib/icalendar/freebusy.rb:5
class Icalendar::Freebusy < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:21
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:16
  def append_attendee(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:17
  def append_comment(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:18
  def append_freebusy(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:19
  def append_request_status(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:16
  def attendee; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:16
  def attendee=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:17
  def comment; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:17
  def comment=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:10
  def contact; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:10
  def contact=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:12
  def dtend; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:12
  def dtend=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:7
  def dtstamp; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:7
  def dtstamp=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:11
  def dtstart; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:11
  def dtstart=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:18
  def freebusy; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:18
  def freebusy=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:13
  def organizer; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:13
  def organizer=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:19
  def request_status; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:19
  def request_status=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:8
  def uid; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:8
  def uid=(value); end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:14
  def url; end

  # pkg:gem/icalendar#lib/icalendar/freebusy.rb:14
  def url=(value); end
end

# pkg:gem/icalendar#lib/icalendar/has_components.rb:5
module Icalendar::HasComponents
  mixes_in_class_methods ::Icalendar::HasComponents::ClassMethods

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:14
  def initialize(*args); end

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:19
  def add_component(c); end

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:26
  def add_custom_component(component_name, c); end

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:33
  def custom_component(component_name); end

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:40
  def method_missing(method, *args, &block); end

  private

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:53
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  class << self
    # pkg:gem/icalendar#lib/icalendar/has_components.rb:7
    def included(base); end
  end
end

# pkg:gem/icalendar#lib/icalendar/has_components.rb:58
module Icalendar::HasComponents::ClassMethods
  # pkg:gem/icalendar#lib/icalendar/has_components.rb:63
  def component(singular_name, find_by = T.unsafe(nil), klass = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/has_components.rb:59
  def components; end
end

# pkg:gem/icalendar#lib/icalendar/has_components.rb:37
Icalendar::HasComponents::METHOD_MISSING_ADD_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/has_components.rb:38
Icalendar::HasComponents::METHOD_MISSING_X_FLAG_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/has_properties.rb:5
module Icalendar::HasProperties
  mixes_in_class_methods ::Icalendar::HasProperties::ClassMethods

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:14
  def initialize(*args); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:47
  def append_custom_property(property_name, value); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:43
  def custom_property(property_name); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:60
  def method_missing(method, *args, &block); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:34
  def property(property_name); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:19
  def valid?(strict = T.unsafe(nil)); end

  private

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:174
  def map_property_value(value, klass, multi_valued, new_property); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:73
  def respond_to_missing?(method, include_private = T.unsafe(nil)); end

  class << self
    # pkg:gem/icalendar#lib/icalendar/has_properties.rb:7
    def included(base); end
  end
end

# pkg:gem/icalendar#lib/icalendar/has_properties.rb:77
module Icalendar::HasProperties::ClassMethods
  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:102
  def default_property_types; end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:144
  def multi_property(prop, klass, new_property); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:86
  def multiple_properties; end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:98
  def mutex_properties; end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:122
  def mutually_exclusive_properties(*properties); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:126
  def optional_property(prop, klass = T.unsafe(nil), suggested_single = T.unsafe(nil), new_property = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:118
  def optional_single_property(prop, klass = T.unsafe(nil), new_property = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:78
  def properties; end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:112
  def required_multi_property(prop, klass = T.unsafe(nil), validator = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:90
  def required_properties; end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:106
  def required_property(prop, klass = T.unsafe(nil), validator = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:82
  def single_properties; end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:131
  def single_property(prop, klass, new_property); end

  # pkg:gem/icalendar#lib/icalendar/has_properties.rb:94
  def suggested_single_properties; end
end

# pkg:gem/icalendar#lib/icalendar/journal.rb:5
class Icalendar::Journal < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/journal.rb:35
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:23
  def append_attach(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:24
  def append_attendee(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:25
  def append_categories(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:26
  def append_comment(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:27
  def append_contact(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:28
  def append_description(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:29
  def append_exdate(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:33
  def append_image(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:32
  def append_rdate(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:31
  def append_related_to(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:30
  def append_request_status(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:22
  def append_rrule(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:23
  def attach; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:23
  def attach=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:24
  def attendee; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:24
  def attendee=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:25
  def categories; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:25
  def categories=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:11
  def color; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:11
  def color=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:26
  def comment; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:26
  def comment=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:27
  def contact; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:27
  def contact=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:12
  def created; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:12
  def created=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:28
  def description; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:28
  def description=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:7
  def dtstamp; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:7
  def dtstamp=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:13
  def dtstart; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:13
  def dtstart=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:29
  def exdate; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:29
  def exdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:33
  def image; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:33
  def image=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:10
  def ip_class; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:10
  def ip_class=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:14
  def last_modified; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:14
  def last_modified=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:15
  def organizer; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:15
  def organizer=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:32
  def rdate; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:32
  def rdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:16
  def recurrence_id; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:16
  def recurrence_id=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:31
  def related_to; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:31
  def related_to=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:30
  def request_status; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:30
  def request_status=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:22
  def rrule; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:22
  def rrule=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:17
  def sequence; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:17
  def sequence=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:18
  def status; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:18
  def status=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:19
  def summary; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:19
  def summary=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:8
  def uid; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:8
  def uid=(value); end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:20
  def url; end

  # pkg:gem/icalendar#lib/icalendar/journal.rb:20
  def url=(value); end
end

# pkg:gem/icalendar#lib/icalendar/logger.rb:8
class Icalendar::Logger < ::SimpleDelegator
  # pkg:gem/icalendar#lib/icalendar/logger.rb:10
  def initialize(sink, level = T.unsafe(nil)); end
end

# pkg:gem/icalendar#lib/icalendar.rb:7
Icalendar::MAX_LINE_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/icalendar#lib/icalendar/marshable.rb:4
module Icalendar::Marshable
  mixes_in_class_methods ::Icalendar::Marshable::ClassMethods

  # pkg:gem/icalendar#lib/icalendar/marshable.rb:9
  def marshal_dump; end

  # pkg:gem/icalendar#lib/icalendar/marshable.rb:18
  def marshal_load(serialized); end

  class << self
    # pkg:gem/icalendar#lib/icalendar/marshable.rb:5
    def included(base); end
  end
end

# pkg:gem/icalendar#lib/icalendar/marshable.rb:26
module Icalendar::Marshable::ClassMethods
  # pkg:gem/icalendar#lib/icalendar/marshable.rb:31
  def transient_variable(name); end

  # pkg:gem/icalendar#lib/icalendar/marshable.rb:27
  def transient_variables; end
end

# pkg:gem/icalendar#lib/icalendar/offset.rb:4
class Icalendar::Offset
  # pkg:gem/icalendar#lib/icalendar/offset.rb:19
  def initialize(tzid, value, timezone_store); end

  # pkg:gem/icalendar#lib/icalendar/offset.rb:25
  def normalized_tzid; end

  private

  # pkg:gem/icalendar#lib/icalendar/offset.rb:33
  def support_classes_defined?; end

  # pkg:gem/icalendar#lib/icalendar/offset.rb:31
  def timezone_store; end

  # pkg:gem/icalendar#lib/icalendar/offset.rb:31
  def tzid; end

  # pkg:gem/icalendar#lib/icalendar/offset.rb:31
  def value; end

  class << self
    # pkg:gem/icalendar#lib/icalendar/offset.rb:5
    def build(value, params, timezone_store); end
  end
end

# pkg:gem/icalendar#lib/icalendar/offset/active_support_exact.rb:5
class Icalendar::Offset::ActiveSupportExact < ::Icalendar::Offset
  # pkg:gem/icalendar#lib/icalendar/offset/active_support_exact.rb:10
  def normalized_value; end

  # pkg:gem/icalendar#lib/icalendar/offset/active_support_exact.rb:6
  def valid?; end

  private

  # pkg:gem/icalendar#lib/icalendar/offset/active_support_exact.rb:18
  def tz; end
end

# pkg:gem/icalendar#lib/icalendar/offset/active_support_partial.rb:5
class Icalendar::Offset::ActiveSupportPartial < ::Icalendar::Offset
  # pkg:gem/icalendar#lib/icalendar/offset/active_support_partial.rb:16
  def normalized_tzid; end

  # pkg:gem/icalendar#lib/icalendar/offset/active_support_partial.rb:10
  def normalized_value; end

  # pkg:gem/icalendar#lib/icalendar/offset/active_support_partial.rb:6
  def valid?; end

  private

  # pkg:gem/icalendar#lib/icalendar/offset/active_support_partial.rb:22
  def tz; end
end

# pkg:gem/icalendar#lib/icalendar/offset/null.rb:5
class Icalendar::Offset::Null < ::Icalendar::Offset
  # pkg:gem/icalendar#lib/icalendar/offset/null.rb:10
  def normalized_value; end

  # pkg:gem/icalendar#lib/icalendar/offset/null.rb:6
  def valid?; end
end

# pkg:gem/icalendar#lib/icalendar/offset/time_zone_store.rb:5
class Icalendar::Offset::TimeZoneStore < ::Icalendar::Offset
  # pkg:gem/icalendar#lib/icalendar/offset/time_zone_store.rb:10
  def normalized_value; end

  # pkg:gem/icalendar#lib/icalendar/offset/time_zone_store.rb:6
  def valid?; end

  private

  # pkg:gem/icalendar#lib/icalendar/offset/time_zone_store.rb:24
  def tz_info; end
end

# pkg:gem/icalendar#lib/icalendar/offset/windows_to_iana.rb:13
class Icalendar::Offset::WindowsToIana < ::Icalendar::Offset
  # pkg:gem/icalendar#lib/icalendar/offset/windows_to_iana.rb:133
  def normalized_tzid; end

  # pkg:gem/icalendar#lib/icalendar/offset/windows_to_iana.rb:127
  def normalized_value; end

  # pkg:gem/icalendar#lib/icalendar/offset/windows_to_iana.rb:123
  def valid?; end

  private

  # pkg:gem/icalendar#lib/icalendar/offset/windows_to_iana.rb:139
  def tz; end
end

# pkg:gem/icalendar#lib/icalendar/offset/windows_to_iana.rb:14
Icalendar::Offset::WindowsToIana::WINDOWS_TO_IANA = T.let(T.unsafe(nil), Hash)

# pkg:gem/icalendar#lib/icalendar/parser.rb:8
class Icalendar::Parser
  # pkg:gem/icalendar#lib/icalendar/parser.rb:29
  def initialize(source, strict = T.unsafe(nil), verbose = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:9
  def component_class=(_arg0); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:111
  def get_wrapper_class(component, fields); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:45
  def parse; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:56
  def parse_property(component, fields = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:10
  def source; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:10
  def strict; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:128
  def strict?; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:10
  def timezone_store; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:10
  def verbose; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:132
  def verbose?; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:104
  def wrap_in_array?(klass, value, multi_property); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:83
  def wrap_property_value(component, fields, multi_property); end

  private

  # pkg:gem/icalendar#lib/icalendar/parser.rb:138
  def component_class; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:174
  def next_fields; end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:144
  def parse_component(component); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:201
  def parse_fields(input); end

  # pkg:gem/icalendar#lib/icalendar/parser.rb:167
  def read_in_data; end

  class << self
    # pkg:gem/icalendar#lib/icalendar/parser.rb:14
    def clean_bad_wrapping(source); end
  end
end

# pkg:gem/icalendar#lib/icalendar/parser.rb:194
Icalendar::Parser::BAD_LINE = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:196
Icalendar::Parser::BAD_LINE_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:12
Icalendar::Parser::CLEAN_BAD_WRAPPING_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:109
Icalendar::Parser::GET_WRAPPER_CLASS_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:193
Icalendar::Parser::LINE = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:195
Icalendar::Parser::LINE_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:187
Icalendar::Parser::NAME = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:171
Icalendar::Parser::NEXT_FIELDS_TAB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:172
Icalendar::Parser::NEXT_FIELDS_WHITESPACE_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:191
Icalendar::Parser::PARAM = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:197
Icalendar::Parser::PARAM_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:142
Icalendar::Parser::PARSE_COMPONENT_KLASS_NAME_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:189
Icalendar::Parser::PTEXT = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:190
Icalendar::Parser::PVALUE = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:199
Icalendar::Parser::PVALUE_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:198
Icalendar::Parser::PVALUE_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:234
class Icalendar::Parser::ParseError < ::RuntimeError; end

# pkg:gem/icalendar#lib/icalendar/parser.rb:188
Icalendar::Parser::QSTR = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:192
Icalendar::Parser::VALUE = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/parser.rb:101
Icalendar::Parser::WRAP_IN_ARRAY_REGEX_1 = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:102
Icalendar::Parser::WRAP_IN_ARRAY_REGEX_2 = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:79
Icalendar::Parser::WRAP_PROPERTY_VALUE_DELIMETER_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/parser.rb:80
Icalendar::Parser::WRAP_PROPERTY_VALUE_SPLIT_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/timezone.rb:7
class Icalendar::Timezone < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/timezone.rb:77
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:74
  def add_daylight(c); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:75
  def add_standard(c); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:74
  def daylight(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:117
  def daylight_for(local); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:74
  def daylights; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:74
  def has_daylight?; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:75
  def has_standard?; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:71
  def last_modified; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:71
  def last_modified=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:88
  def offset_for_local(local); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:75
  def standard(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:109
  def standard_for(local); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:75
  def standards; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:69
  def tzid; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:69
  def tzid=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:72
  def tzurl; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:72
  def tzurl=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:81
  def valid?(strict = T.unsafe(nil)); end
end

# pkg:gem/icalendar#lib/icalendar/timezone.rb:51
class Icalendar::Timezone::Daylight < ::Icalendar::Component
  include ::Icalendar::Marshable
  include ::Icalendar::Timezone::TzProperties
  extend ::Icalendar::Marshable::ClassMethods

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:55
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:16
  def append_comment(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:17
  def append_rdate(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:15
  def append_rrule(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:18
  def append_tzname(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:16
  def comment; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:16
  def comment=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:11
  def dtstart; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:11
  def dtstart=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:17
  def rdate; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:17
  def rdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:15
  def rrule; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:15
  def rrule=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:18
  def tzname; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:18
  def tzname=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:12
  def tzoffsetfrom; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:12
  def tzoffsetfrom=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:13
  def tzoffsetto; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:13
  def tzoffsetto=(value); end
end

# pkg:gem/icalendar#lib/icalendar/timezone.rb:59
class Icalendar::Timezone::Standard < ::Icalendar::Component
  include ::Icalendar::Marshable
  include ::Icalendar::Timezone::TzProperties
  extend ::Icalendar::Marshable::ClassMethods

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:63
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:16
  def append_comment(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:17
  def append_rdate(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:15
  def append_rrule(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:18
  def append_tzname(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:16
  def comment; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:16
  def comment=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:11
  def dtstart; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:11
  def dtstart=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:17
  def rdate; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:17
  def rdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:15
  def rrule; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:15
  def rrule=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:18
  def tzname; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:18
  def tzname=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:12
  def tzoffsetfrom; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:12
  def tzoffsetfrom=(value); end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:13
  def tzoffsetto; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:13
  def tzoffsetto=(value); end
end

# pkg:gem/icalendar#lib/icalendar/timezone.rb:8
module Icalendar::Timezone::TzProperties
  # pkg:gem/icalendar#lib/icalendar/timezone.rb:25
  def occurrences; end

  # pkg:gem/icalendar#lib/icalendar/timezone.rb:36
  def previous_occurrence(from); end

  class << self
    # pkg:gem/icalendar#lib/icalendar/timezone.rb:9
    def included(base); end
  end
end

# pkg:gem/icalendar#lib/icalendar/timezone_store.rb:7
class Icalendar::TimezoneStore < ::SimpleDelegator
  # pkg:gem/icalendar#lib/icalendar/timezone_store.rb:9
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/timezone_store.rb:32
  def retrieve(tzid); end

  # pkg:gem/icalendar#lib/icalendar/timezone_store.rb:28
  def store(timezone); end

  class << self
    # pkg:gem/icalendar#lib/icalendar/timezone_store.rb:13
    def instance; end

    # pkg:gem/icalendar#lib/icalendar/timezone_store.rb:23
    def retrieve(tzid); end

    # pkg:gem/icalendar#lib/icalendar/timezone_store.rb:18
    def store(timezone); end
  end
end

# pkg:gem/icalendar#lib/icalendar/todo.rb:5
class Icalendar::Todo < ::Icalendar::Component
  # pkg:gem/icalendar#lib/icalendar/todo.rb:49
  def initialize; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:47
  def add_alarm(c); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:47
  def alarm(c = T.unsafe(nil), &block); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:47
  def alarms; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:34
  def append_attach(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:35
  def append_attendee(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:36
  def append_categories(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:37
  def append_comment(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:44
  def append_conference(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:38
  def append_contact(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:39
  def append_exdate(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:45
  def append_image(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:43
  def append_rdate(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:41
  def append_related_to(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:40
  def append_request_status(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:42
  def append_resources(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:33
  def append_rrule(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:34
  def attach; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:34
  def attach=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:35
  def attendee; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:35
  def attendee=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:36
  def categories; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:36
  def categories=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:17
  def color; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:17
  def color=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:37
  def comment; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:37
  def comment=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:18
  def completed; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:18
  def completed=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:44
  def conference; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:44
  def conference=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:38
  def contact; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:38
  def contact=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:19
  def created; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:19
  def created=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:20
  def description; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:20
  def description=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:6
  def dtstamp; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:6
  def dtstamp=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:9
  def dtstart; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:9
  def dtstart=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:12
  def due; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:12
  def due=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:13
  def duration; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:13
  def duration=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:39
  def exdate; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:39
  def exdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:21
  def geo; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:21
  def geo=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:47
  def has_alarm?; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:45
  def image; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:45
  def image=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:16
  def ip_class; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:16
  def ip_class=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:22
  def last_modified; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:22
  def last_modified=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:23
  def location; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:23
  def location=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:24
  def organizer; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:24
  def organizer=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:25
  def percent_complete; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:25
  def percent_complete=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:26
  def priority; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:26
  def priority=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:43
  def rdate; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:43
  def rdate=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:27
  def recurrence_id; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:27
  def recurrence_id=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:41
  def related_to; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:41
  def related_to=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:40
  def request_status; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:40
  def request_status=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:42
  def resources; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:42
  def resources=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:33
  def rrule; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:33
  def rrule=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:28
  def sequence; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:28
  def sequence=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:29
  def status; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:29
  def status=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:30
  def summary; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:30
  def summary=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:7
  def uid; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:7
  def uid=(value); end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:31
  def url; end

  # pkg:gem/icalendar#lib/icalendar/todo.rb:31
  def url=(value); end
end

# pkg:gem/icalendar#lib/icalendar/version.rb:5
Icalendar::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/value.rb:9
class Icalendar::Value < ::SimpleDelegator
  # pkg:gem/icalendar#lib/icalendar/value.rb:13
  def initialize(value, params = T.unsafe(nil), context = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:49
  def ==(other); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:11
  def context; end

  # pkg:gem/icalendar#lib/icalendar/value.rb:11
  def context=(_arg0); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:19
  def ical_param(key, value); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:11
  def ical_params; end

  # pkg:gem/icalendar#lib/icalendar/value.rb:11
  def ical_params=(_arg0); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:32
  def params_ical; end

  # pkg:gem/icalendar#lib/icalendar/value.rb:27
  def to_ical(default_type); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:23
  def value; end

  # pkg:gem/icalendar#lib/icalendar/value.rb:45
  def value_type; end

  private

  # pkg:gem/icalendar#lib/icalendar/value.rb:74
  def escape_param_value(value); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:59
  def needs_value_type?(default_type); end

  # pkg:gem/icalendar#lib/icalendar/value.rb:63
  def param_ical(name, param_value); end

  class << self
    # pkg:gem/icalendar#lib/icalendar/value.rb:41
    def value_type; end
  end
end

# pkg:gem/icalendar#lib/icalendar/value.rb:72
Icalendar::Value::ESCAPE_PARAM_VALUE_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/value.rb:38
Icalendar::Value::VALUE_TYPE_GSUB_REGEX_1 = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/value.rb:39
Icalendar::Value::VALUE_TYPE_GSUB_REGEX_2 = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:4
module Icalendar::Values; end

# pkg:gem/icalendar#lib/icalendar/values/binary.rb:8
class Icalendar::Values::Binary < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/binary.rb:10
  def params_ical; end

  # pkg:gem/icalendar#lib/icalendar/values/binary.rb:16
  def value_ical; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/binary.rb:28
  def base64?; end
end

# pkg:gem/icalendar#lib/icalendar/values/binary.rb:26
Icalendar::Values::Binary::BASE_64_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/boolean.rb:6
class Icalendar::Values::Boolean < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/boolean.rb:8
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/boolean.rb:12
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/cal_address.rb:6
class Icalendar::Values::CalAddress < ::Icalendar::Values::Uri; end

# pkg:gem/icalendar#lib/icalendar/values/date.rb:8
class Icalendar::Values::Date < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/date.rb:11
  def initialize(value, params = T.unsafe(nil), *args); end

  # pkg:gem/icalendar#lib/icalendar/values/date.rb:32
  def <=>(other); end

  # pkg:gem/icalendar#lib/icalendar/values/date.rb:28
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/date.rb:9
Icalendar::Values::Date::FORMAT = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/date.rb:40
class Icalendar::Values::Date::FormatError < ::ArgumentError; end

# DateOrDateTime can be used to set an attribute to either a Date or a DateTime value.
# It should not be used without also invoking the `call` method.
#
# pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:6
class Icalendar::Values::DateOrDateTime < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:8
  def call; end

  # pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:16
  def params_ical; end

  # pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:12
  def value_ical; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:30
  def needs_value_type?(default_type); end

  # pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:22
  def parsed; end

  # pkg:gem/icalendar#lib/icalendar/values/date_or_date_time.rb:34
  def value_type; end
end

# pkg:gem/icalendar#lib/icalendar/values/date_time.rb:9
class Icalendar::Values::DateTime < ::Icalendar::Value
  include ::Icalendar::Values::Helpers::TimeWithZone

  # pkg:gem/icalendar#lib/icalendar/values/date_time.rb:14
  def initialize(value, params = T.unsafe(nil), *args); end

  # pkg:gem/icalendar#lib/icalendar/values/date_time.rb:40
  def <=>(other); end

  # pkg:gem/icalendar#lib/icalendar/values/date_time.rb:48
  def utc?; end

  # pkg:gem/icalendar#lib/icalendar/values/date_time.rb:32
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/date_time.rb:12
Icalendar::Values::DateTime::FORMAT = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/date_time.rb:52
class Icalendar::Values::DateTime::FormatError < ::ArgumentError; end

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:8
class Icalendar::Values::Duration < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/duration.rb:10
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/duration.rb:18
  def past?; end

  # pkg:gem/icalendar#lib/icalendar/values/duration.rb:22
  def value_ical; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/duration.rb:48
  def parse_fields(value); end

  # pkg:gem/icalendar#lib/icalendar/values/duration.rb:37
  def time?; end
end

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:43
Icalendar::Values::Duration::DURATION_DAYS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:44
Icalendar::Values::Duration::DURATION_HOURS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:45
Icalendar::Values::Duration::DURATION_MINUTES_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:41
Icalendar::Values::Duration::DURATION_PAST_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:46
Icalendar::Values::Duration::DURATION_SECONDS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/duration.rb:42
Icalendar::Values::Duration::DURATION_WEEKS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/float.rb:6
class Icalendar::Values::Float < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/float.rb:8
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/float.rb:12
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:5
module Icalendar::Values::Helpers; end

# pkg:gem/icalendar#lib/icalendar/values/helpers/active_support_time_with_zone_adapter.rb:6
class Icalendar::Values::Helpers::ActiveSupportTimeWithZoneAdapter < ::ActiveSupport::TimeWithZone; end

# pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:7
class Icalendar::Values::Helpers::Array < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:11
  def initialize(value, klass, params = T.unsafe(nil), context = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:32
  def params_ical; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:45
  def valid?; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:9
  def value_delimiter; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:39
  def value_ical; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:50
  def value_type; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/helpers/array.rb:56
  def needs_value_type?(default_type); end
end

# pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:19
module Icalendar::Values::Helpers::TimeWithZone
  # pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:22
  def initialize(value, params = T.unsafe(nil), context = T.unsafe(nil)); end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:38
  def __getobj__; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:49
  def params_ical; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:20
  def timezone_store; end

  # pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:20
  def tz_utc; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/helpers/time_with_zone.rb:56
  def set_offset?; end
end

# pkg:gem/icalendar#lib/icalendar/values/integer.rb:6
class Icalendar::Values::Integer < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/integer.rb:8
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/integer.rb:12
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/period.rb:6
class Icalendar::Values::Period < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/period.rb:10
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:41
  def duration; end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:45
  def duration=(v); end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:33
  def explicit_end; end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:37
  def explicit_end=(v); end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:25
  def period_start; end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:29
  def period_start=(v); end

  # pkg:gem/icalendar#lib/icalendar/values/period.rb:21
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/period.rb:8
Icalendar::Values::Period::PERIOD_LAST_PART_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:8
class Icalendar::Values::Recur < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/recur.rb:15
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/recur.rb:23
  def valid?; end

  # pkg:gem/icalendar#lib/icalendar/values/recur.rb:29
  def value_ical; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/recur.rb:64
  def parse_fields(value); end
end

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:10
Icalendar::Values::Recur::DAYNAME = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:12
Icalendar::Values::Recur::MONTHDAY = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:9
Icalendar::Values::Recur::NUM_LIST = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:56
Icalendar::Values::Recur::PARSE_FIELDS_BY_DAY_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:55
Icalendar::Values::Recur::PARSE_FIELDS_BY_HOUR_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:54
Icalendar::Values::Recur::PARSE_FIELDS_BY_MINUTE_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:57
Icalendar::Values::Recur::PARSE_FIELDS_BY_MONTH_DAY_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:60
Icalendar::Values::Recur::PARSE_FIELDS_BY_MONTH_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:53
Icalendar::Values::Recur::PARSE_FIELDS_BY_SECOND_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:61
Icalendar::Values::Recur::PARSE_FIELDS_BY_SET_POSITON_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:59
Icalendar::Values::Recur::PARSE_FIELDS_BY_WEEK_NUMBER_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:62
Icalendar::Values::Recur::PARSE_FIELDS_BY_WEEK_START_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:58
Icalendar::Values::Recur::PARSE_FIELDS_BY_YEAR_DAY_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:51
Icalendar::Values::Recur::PARSE_FIELDS_COUNT_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:49
Icalendar::Values::Recur::PARSE_FIELDS_FREQUENCY_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:52
Icalendar::Values::Recur::PARSE_FIELDS_INTERVAL_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:50
Icalendar::Values::Recur::PARSE_FIELDS_UNTIL_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:11
Icalendar::Values::Recur::WEEKDAY = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/recur.rb:13
Icalendar::Values::Recur::YEARDAY = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/text.rb:5
class Icalendar::Values::Text < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/text.rb:8
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/text.rb:16
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/text.rb:6
Icalendar::Values::Text::UNESCAPE_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/text.rb:14
Icalendar::Values::Text::VALUE_ICAL_CARRIAGE_RETURN_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/time.rb:9
class Icalendar::Values::Time < ::Icalendar::Value
  include ::Icalendar::Values::Helpers::TimeWithZone

  # pkg:gem/icalendar#lib/icalendar/values/time.rb:14
  def initialize(value, params = T.unsafe(nil), *args); end

  # pkg:gem/icalendar#lib/icalendar/values/time.rb:25
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/time.rb:12
Icalendar::Values::Time::FORMAT = T.let(T.unsafe(nil), String)

# pkg:gem/icalendar#lib/icalendar/values/uri.rb:8
class Icalendar::Values::Uri < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/uri.rb:11
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/uri.rb:16
  def value_ical; end
end

# pkg:gem/icalendar#lib/icalendar/values/uri.rb:9
Icalendar::Values::Uri::CONTROL_BYTES_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:7
class Icalendar::Values::UtcOffset < ::Icalendar::Value
  # pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:8
  def initialize(value, *args); end

  # pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:17
  def behind?; end

  # pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:26
  def to_s; end

  # pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:22
  def value_ical; end

  private

  # pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:44
  def parse_fields(value); end

  # pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:37
  def zero_offset?; end
end

# pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:41
Icalendar::Values::UtcOffset::PARSE_FIELDS_MD_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/icalendar#lib/icalendar/values/utc_offset.rb:42
Icalendar::Values::UtcOffset::PARSE_FIELDS_WHITESPACE_GSUB_REGEX = T.let(T.unsafe(nil), Regexp)
