# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ice_cube` gem.
# Please instead update this file by running `bin/tapioca gem ice_cube`.


# pkg:gem/ice_cube#lib/ice_cube/deprecated.rb:1
module IceCube
  class << self
    # Retain backwards compatibility for schedules exported from older versions
    # This represents the version number, 11 = 0.11, 1.0 will be 100
    #
    # pkg:gem/ice_cube#lib/ice_cube.rb:83
    def compatibility; end

    # pkg:gem/ice_cube#lib/ice_cube.rb:87
    def compatibility=(version); end

    # Defines the format used by IceCube when printing out Schedule#to_s.
    # Defaults to '%B %e, %Y'
    #
    # pkg:gem/ice_cube#lib/ice_cube.rb:72
    def to_s_time_format; end

    # Sets the format used by IceCube when printing out Schedule#to_s.
    #
    # pkg:gem/ice_cube#lib/ice_cube.rb:77
    def to_s_time_format=(format); end
  end
end

# An exception for when a count on a Rule is passed
#
# pkg:gem/ice_cube#lib/ice_cube/errors/count_exceeded.rb:3
class IceCube::CountExceeded < ::StopIteration; end

# pkg:gem/ice_cube#lib/ice_cube/rules/daily_rule.rb:2
class IceCube::DailyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfMonth
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::DailyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/daily_rule.rb:14
  def initialize(interval = T.unsafe(nil)); end
end

# pkg:gem/ice_cube#lib/ice_cube/deprecated.rb:2
module IceCube::Deprecated
  # Deprecate a defined method
  # @param [Symbol] name - name of deprecated method
  # @param [Symbol] replacement - name of the desired replacement
  #
  # pkg:gem/ice_cube#lib/ice_cube/deprecated.rb:17
  def deprecated(name, replacement); end

  # Define a deprecated alias for a method
  # @param [Symbol] name - name of method to define
  # @param [Symbol] replacement - name of method to replace (alias)
  #
  # pkg:gem/ice_cube#lib/ice_cube/deprecated.rb:6
  def deprecated_alias(name, replacement); end

  class << self
    # pkg:gem/ice_cube#lib/ice_cube/deprecated.rb:28
    def schedule_options(schedule, options); end
  end
end

# Find keys by symbol or string without symbolizing user input
# Due to the serialization format of ice_cube, this limited implementation
# is entirely sufficient
#
# pkg:gem/ice_cube#lib/ice_cube/flexible_hash.rb:8
class IceCube::FlexibleHash < ::SimpleDelegator
  # pkg:gem/ice_cube#lib/ice_cube/flexible_hash.rb:9
  def [](key); end

  # pkg:gem/ice_cube#lib/ice_cube/flexible_hash.rb:19
  def delete(key); end

  # pkg:gem/ice_cube#lib/ice_cube/flexible_hash.rb:14
  def fetch(key); end

  private

  # pkg:gem/ice_cube#lib/ice_cube/flexible_hash.rb:26
  def _match_key(key); end
end

# pkg:gem/ice_cube#lib/ice_cube/builders/hash_builder.rb:2
class IceCube::HashBuilder
  # pkg:gem/ice_cube#lib/ice_cube/builders/hash_builder.rb:3
  def initialize(rule = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/hash_builder.rb:11
  def []=(key, value); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/hash_builder.rb:19
  def to_hash; end

  # pkg:gem/ice_cube#lib/ice_cube/builders/hash_builder.rb:7
  def validations; end

  # pkg:gem/ice_cube#lib/ice_cube/builders/hash_builder.rb:15
  def validations_array(type); end
end

# pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:2
class IceCube::HashParser
  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:5
  def initialize(original_hash); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:3
  def hash; end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:9
  def to_schedule; end

  private

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:42
  def apply_duration(schedule, data); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:47
  def apply_end_time(schedule, data); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:61
  def apply_exrules(schedule, data); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:77
  def apply_extimes(schedule, data); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:52
  def apply_rrules(schedule, data); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:70
  def apply_rtimes(schedule, data); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:24
  def normalize_keys(hash); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/hash_parser.rb:84
  def parse_time(time); end
end

# pkg:gem/ice_cube#lib/ice_cube/rules/hourly_rule.rb:2
class IceCube::HourlyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfMonth
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::DayOfYear
  include ::IceCube::Validations::HourlyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/hourly_rule.rb:14
  def initialize(interval = T.unsafe(nil)); end
end

# pkg:gem/ice_cube#lib/ice_cube/i18n.rb:7
IceCube::I18n = I18n

# pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:2
class IceCube::IcalBuilder
  # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:5
  def initialize; end

  # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:13
  def [](key); end

  # Build for a single rule entry
  #
  # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:18
  def to_s; end

  class << self
    # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:9
    def fixnum_to_ical_day(num); end

    # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:45
    def ical_duration(duration); end

    # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:36
    def ical_format(time, force_utc); end

    # pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:31
    def ical_utc_format(time); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/builders/ical_builder.rb:3
IceCube::IcalBuilder::ICAL_DAYS = T.let(T.unsafe(nil), Array)

# pkg:gem/ice_cube#lib/ice_cube/parsers/ical_parser.rb:2
class IceCube::IcalParser
  class << self
    # pkg:gem/ice_cube#lib/ice_cube/parsers/ical_parser.rb:29
    def rule_from_ical(ical); end

    # pkg:gem/ice_cube#lib/ice_cube/parsers/ical_parser.rb:3
    def schedule_from_ical(ical_string, options = T.unsafe(nil)); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:2
class IceCube::InputAlignment
  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:3
  def initialize(rule, value, rule_part); end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:9
  def rule; end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:9
  def rule_part; end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:9
  def value; end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:11
  def verify(freq, options = T.unsafe(nil), &_arg2); end

  private

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:34
  def fixed_validations; end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:26
  def interval_validation; end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:30
  def interval_value; end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:42
  def verify_freq_alignment(freq); end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:63
  def verify_month_alignment(_freq); end

  # pkg:gem/ice_cube#lib/ice_cube/input_alignment.rb:72
  def verify_wday_alignment(freq); end
end

# pkg:gem/ice_cube#lib/ice_cube/i18n.rb:4
IceCube::LOCALES_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/ice_cube#lib/ice_cube/rules/minutely_rule.rb:2
class IceCube::MinutelyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfMonth
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::DayOfYear
  include ::IceCube::Validations::MinutelyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/minutely_rule.rb:14
  def initialize(interval = T.unsafe(nil)); end
end

# pkg:gem/ice_cube#lib/ice_cube/rules/monthly_rule.rb:2
class IceCube::MonthlyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfMonth
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::MonthlyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/monthly_rule.rb:14
  def initialize(interval = T.unsafe(nil)); end
end

# pkg:gem/ice_cube#lib/ice_cube/null_i18n.rb:4
module IceCube::NullI18n
  class << self
    # pkg:gem/ice_cube#lib/ice_cube/null_i18n.rb:30
    def config; end

    # pkg:gem/ice_cube#lib/ice_cube/null_i18n.rb:25
    def l(date_or_time, options = T.unsafe(nil)); end

    # pkg:gem/ice_cube#lib/ice_cube/null_i18n.rb:5
    def t(key, options = T.unsafe(nil)); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube.rb:67
IceCube::ONE_DAY = T.let(T.unsafe(nil), Integer)

# pkg:gem/ice_cube#lib/ice_cube.rb:66
IceCube::ONE_HOUR = T.let(T.unsafe(nil), Integer)

# pkg:gem/ice_cube#lib/ice_cube.rb:65
IceCube::ONE_MINUTE = T.let(T.unsafe(nil), Integer)

# Define some useful constants
#
# pkg:gem/ice_cube#lib/ice_cube.rb:64
IceCube::ONE_SECOND = T.let(T.unsafe(nil), Integer)

# pkg:gem/ice_cube#lib/ice_cube.rb:68
IceCube::ONE_WEEK = T.let(T.unsafe(nil), Integer)

# Wraps start_time and end_time in a single concept concerning the duration.
# This delegates to the enclosed start_time so it behaves like a normal Time
# in almost all situations, however:
#
# Without ActiveSupport, it's necessary to cast the occurrence using
# +#to_time+ before doing arithmetic, else Time will try to subtract it
# using +#to_i+ and return a new time instead.
#
#     Time.now - Occurrence.new(start_time) # => 1970-01-01 01:00:00
#     Time.now - Occurrence.new(start_time).to_time # => 3600
#
# When ActiveSupport::Time core extensions are loaded, it's possible to
# subtract an Occurrence object directly from a Time to get the difference:
#
#     Time.now - Occurrence.new(start_time) # => 3600
#
# pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:20
class IceCube::Occurrence < ::SimpleDelegator
  include ::Comparable

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:32
  def initialize(start_time, end_time = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:42
  def <=>(other); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:67
  def comparable_time; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:62
  def cover?(other); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:71
  def duration; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:28
  def end_time; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:29
  def first; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:65
  def include?(other); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:51
  def intersects?(other); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:46
  def is_a?(klass); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:49
  def kind_of?(klass); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:30
  def last; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:96
  def overnight?; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:28
  def start_time; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:38
  def to_i; end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:75
  def to_range; end

  # Shows both the start and end time if there is a duration.
  # Optional format argument (e.g. :long, :short) supports Rails
  # time formats and is only used when ActiveSupport is available.
  #
  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:87
  def to_s(format = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:79
  def to_time; end

  class << self
    # Report class name as 'Time' to thwart type checking.
    #
    # pkg:gem/ice_cube#lib/ice_cube/occurrence.rb:24
    def name; end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/rule.rb:4
class IceCube::Rule
  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:20
  def ==(other); end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:25
  def hash; end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:52
  def next_time(time, schedule, closing_time); end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:55
  def on?(time, schedule); end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:12
  def reset; end

  # Is this a terminating schedule?
  #
  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:16
  def terminating?; end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:48
  def to_hash; end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:29
  def to_ical; end

  # Yaml implementation
  #
  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:39
  def to_yaml(*args); end

  # pkg:gem/ice_cube#lib/ice_cube/rule.rb:10
  def uses; end

  class << self
    # Daily Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:118
    def daily(interval = T.unsafe(nil)); end

    # Convert from a hash and create a rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:61
    def from_hash(original_hash); end

    # Convert from ical string and create a rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:34
    def from_ical(ical); end

    # From yaml
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:44
    def from_yaml(yaml); end

    # Hourly Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:113
    def hourly(interval = T.unsafe(nil)); end

    # Minutely Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:108
    def minutely(interval = T.unsafe(nil)); end

    # Monthly Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:128
    def monthly(interval = T.unsafe(nil)); end

    # Secondly Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:103
    def secondly(interval = T.unsafe(nil)); end

    # Weekly Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:123
    def weekly(interval = T.unsafe(nil), week_start = T.unsafe(nil)); end

    # Yearly Rule
    #
    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:133
    def yearly(interval = T.unsafe(nil)); end

    private

    # pkg:gem/ice_cube#lib/ice_cube/rule.rb:89
    def apply_validation(rule, name, args); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/rule.rb:5
IceCube::Rule::INTERVAL_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/ice_cube#lib/ice_cube/schedule.rb:4
class IceCube::Schedule
  extend ::IceCube::Deprecated

  # Create a new schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:16
  def initialize(start_time = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:397
  def ==(other); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:65
  def add_exception_date(*args, &block); end

  # Add an exception rule to the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:81
  def add_exception_rule(rule); end

  # Add an exception time to the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:57
  def add_exception_time(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:54
  def add_recurrence_date(*args, &block); end

  # Add a recurrence rule to the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:68
  def add_recurrence_rule(rule); end

  # Add a recurrence time to the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:46
  def add_recurrence_time(time); end

  # All of the occurrences
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:152
  def all_occurrences; end

  # Emit an enumerator based on the start time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:158
  def all_occurrences_enumerator; end

  # Determine if this schedule conflicts with another schedule
  # @param [IceCube::Schedule] other_schedule - The schedule to compare to
  # @param [Time] closing_time - the last time to consider
  # @return [Boolean] whether or not the schedules conflict at all
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:255
  def conflicts_with?(other_schedule, closing_time = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:37
  def duration; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:41
  def duration=(seconds); end

  # Iterate forever
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:163
  def each_occurrence(&_arg0); end

  # Hook for YAML.dump, enables to_yaml
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:342
  def encode_with(coder); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:13
  def end_date(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:35
  def end_date=(*args, &block); end

  # Get the end time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:12
  def end_time; end

  # Set end_time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:32
  def end_time=(end_time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:394
  def eql?(other); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:131
  def exception_dates(*args, &block); end

  # Get the exception rules
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:100
  def exception_rules; end

  # Get the exception times that are on the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:126
  def exception_times; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:64
  def exdate(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:130
  def exdates(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:85
  def exrule(rule); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:103
  def exrules; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:63
  def extime(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:129
  def extimes; end

  # Get the first n occurrences, or the first occurrence if n is skipped
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:297
  def first(n = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:386
  def hash; end

  # Get the final n occurrences of a terminating schedule
  # or the final one if no n is given
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:304
  def last(n = T.unsafe(nil)); end

  # The next occurrence after now (overridable)
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:175
  def next_occurrence(from = T.unsafe(nil), options = T.unsafe(nil)); end

  # The next n occurrences after now
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:169
  def next_occurrences(num, from = T.unsafe(nil), options = T.unsafe(nil)); end

  # Get all of the occurrences from the start_time up until a
  # given Time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:147
  def occurrences(closing_time); end

  # Occurrences between two times
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:211
  def occurrences_between(begin_time, closing_time, options = T.unsafe(nil)); end

  # Determine if the schedule is occurring at a given time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:241
  def occurring_at?(time); end

  # Return a boolean indicating if an occurrence is occurring between two
  # times, inclusive of its duration. This counts zero-length occurrences
  # that intersect the start of the range and within the range, but not
  # occurrences at the end of the range since none of their duration
  # intersects the range.
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:228
  def occurring_between?(opening_time, closing_time); end

  # Determine if the schedule occurs at a specific time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:292
  def occurs_at?(time); end

  # Return a boolean indicating if an occurrence falls between two times
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:216
  def occurs_between?(begin_time, closing_time, options = T.unsafe(nil)); end

  # Return a boolean indicating if an occurrence falls on a certain date
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:233
  def occurs_on?(date); end

  # The previous occurrence from a given time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:183
  def previous_occurrence(from); end

  # The previous n occurrences before a given time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:190
  def previous_occurrences(num, from); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:53
  def rdate(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:110
  def rdates(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:111
  def recurrence_dates(*args, &block); end

  # Get the recurrence rules
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:94
  def recurrence_rules; end

  # Get the recurrence times that are on the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:106
  def recurrence_times; end

  # The remaining occurrences (same requirements as all_occurrences)
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:198
  def remaining_occurrences(from = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns an enumerator for all remaining occurrences
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:205
  def remaining_occurrences_enumerator(from = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:142
  def remove_exception_date(*args, &block); end

  # Remove an exception rule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:88
  def remove_exception_rule(rule); end

  # Remove an exception time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:134
  def remove_exception_time(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:143
  def remove_exdate(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:141
  def remove_extime(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:123
  def remove_rdate(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:122
  def remove_recurrence_date(*args, &block); end

  # Remove a recurrence rule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:75
  def remove_recurrence_rule(rule); end

  # Remove a recurrence time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:114
  def remove_recurrence_time(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:121
  def remove_rtime(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:72
  def rrule(rule); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:97
  def rrules; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:52
  def rtime(time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:109
  def rtimes; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:9
  def start_date(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:29
  def start_date=(*args, &block); end

  # Get the start time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:8
  def start_time; end

  # Set start_time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:26
  def start_time=(start_time); end

  # Determine if the schedule will end
  # @return [Boolean] true if ending, false if repeating forever
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:382
  def terminating?; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:370
  def to_h; end

  # Convert the schedule to a hash
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:355
  def to_hash; end

  # Serialize this schedule to_ical
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:325
  def to_ical(force_utc = T.unsafe(nil)); end

  # String serialization
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:311
  def to_s; end

  private

  # Find all of the occurrences for the schedule between opening_time
  # and closing_time
  # Iteration is unrolled in pairs to skip duplicate times in end of DST
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:420
  def enumerate_occurrences(opening_time, closing_time = T.unsafe(nil), options = T.unsafe(nil)); end

  # Return a boolean indicating whether or not a specific time
  # is excluded from the schedule
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:466
  def exception_time?(time); end

  # Indicate if any rule needs to be run from the start of time
  # If we have rules with counts, we need to walk from the beginning of time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:459
  def full_required?; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:478
  def implicit_start_occurrence_rule; end

  # Get the next time after (or including) a specific time
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:443
  def next_time(time, closing_time); end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:494
  def recurrence_rules_with_implicit_start_occurrence; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:486
  def recurrence_times_with_start_time; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:482
  def recurrence_times_without_start_time; end

  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:472
  def require_terminating_rules; end

  # Reset all rules for another run
  #
  # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:412
  def reset; end

  class << self
    # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:399
    def dump(schedule); end

    # Load the schedule from a hash
    #
    # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:373
    def from_hash(original_hash, options = T.unsafe(nil)); end

    # Load the schedule from ical
    #
    # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:337
    def from_ical(ical, options = T.unsafe(nil)); end

    # Load the schedule from yaml
    #
    # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:347
    def from_yaml(yaml, options = T.unsafe(nil)); end

    # pkg:gem/ice_cube#lib/ice_cube/schedule.rb:404
    def load(yaml); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/rules/secondly_rule.rb:2
class IceCube::SecondlyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfMonth
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::DayOfYear
  include ::IceCube::Validations::SecondlyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/secondly_rule.rb:14
  def initialize(interval = T.unsafe(nil)); end
end

# pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:2
class IceCube::SingleOccurrenceRule < ::IceCube::Rule
  # pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:5
  def initialize(time); end

  # pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:24
  def full_required?; end

  # pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:14
  def next_time(t, _, closing_time); end

  # Always terminating
  #
  # pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:10
  def terminating?; end

  # pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:3
  def time; end

  # pkg:gem/ice_cube#lib/ice_cube/single_occurrence_rule.rb:20
  def to_hash; end
end

# pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:2
class IceCube::StringBuilder
  extend ::IceCube::StringBuilder::Helpers

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:5
  def initialize; end

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:3
  def base=(_arg0); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:9
  def piece(type, prefix = T.unsafe(nil), suffix = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:13
  def to_s; end

  class << self
    # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:28
    def formatter(type); end

    # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:32
    def register_formatter(type, &formatter); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:37
module IceCube::StringBuilder::Helpers
  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:56
  def literal_ordinal(number); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:48
  def nice_number(number); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:60
  def ordinal(number); end

  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:52
  def ordinalize(number); end

  # influenced by ActiveSupport's to_sentence
  #
  # pkg:gem/ice_cube#lib/ice_cube/builders/string_builder.rb:39
  def sentence(array); end
end

# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:5
module IceCube::TimeUtil
  extend ::IceCube::Deprecated

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:179
  def normalize_weekday(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:164
  def symbol_to_day(*args, &block); end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:154
  def symbol_to_month(*args, &block); end

  class << self
    # Get the beginning of a date
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:137
    def beginning_of_date(date, reference = T.unsafe(nil)); end

    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:31
    def build_in_zone(args, reference); end

    # Get a day of the month in the month of a given time without overflowing
    # into the next month. Accepts days from positive (start of month forward) or
    # negative (from end of month)
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:218
    def day_of_month(value, date); end

    # Get the days in the month for +time
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:197
    def days_in_month(time); end

    # The number of days in n months
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:239
    def days_in_n_months(time, month_distance); end

    # Number of days to n years
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:233
    def days_in_n_years(time, year_distance); end

    # Get the days in the following month for +time
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:203
    def days_in_next_month(time); end

    # Number of days in a year
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:227
    def days_in_year(time); end

    # Count the number of days to the same day of the next month without
    # overflowing shorter months
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:210
    def days_to_next_month(time); end

    # Deserialize a time serialized with serialize_time or in ISO8601 string format
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:102
    def deserialize_time(time_or_hash); end

    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:244
    def dst_change(time); end

    # Get the end of a date
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:142
    def end_of_date(date, reference = T.unsafe(nil)); end

    # Ensure that this is either nil, or a date
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:77
    def ensure_date(date); end

    # Ensure that this is either nil, or a time
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:58
    def ensure_time(time, reference = T.unsafe(nil), date_eod = T.unsafe(nil)); end

    # Get a more precise equality for time objects
    # Ruby provides a Time#hash method, but it fails to account for UTC
    # offset (so the current date may be different) or DST rules (so the
    # hour may be wrong for different schedule occurrences)
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:120
    def hash(time); end

    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:181
    def ical_day_to_symbol(str); end

    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:43
    def match_zone(input_time, reference); end

    # Convert weekday from base sunday to the schedule's week start.
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:176
    def normalize_wday(wday, week_start); end

    # Provides a Time.now without the usec, in the reference zone or utc offset
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:27
    def now(reference = T.unsafe(nil)); end

    # Check the deserialized time offset string against actual local time
    # offset to try and preserve the original offset for plain Ruby Time. If
    # the offset is the same as local we can assume the same original zone and
    # keep it.  If it was serialized with a different offset than local TZ it
    # will lose the zone and not support DST.
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:129
    def restore_deserialized_offset(time, orig_offset_str); end

    # Serialize a time appropriate for storing
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:86
    def serialize_time(time); end

    # Handle discrepancies between various time types
    # - Time has subsec
    # - DateTime does not
    # - ActiveSupport::TimeWithZone can wrap either type, depending on version
    #   or if `parse` or `now`/`local` was used to build it.
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:256
    def subsec(time); end

    # Convert a symbol to a numeric month
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:147
    def sym_to_month(sym); end

    # Convert a symbol to a wday number
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:157
    def sym_to_wday(sym); end

    # Convert wday number to day symbol
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:167
    def wday_to_sym(wday); end

    # Return the count of the number of times wday appears in the month,
    # and which of those time falls on
    #
    # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:189
    def which_occurrence_in_month(time, wday); end
  end
end

# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:24
IceCube::TimeUtil::CLOCK_VALUES = T.let(T.unsafe(nil), Array)

# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:8
IceCube::TimeUtil::DAYS = T.let(T.unsafe(nil), Hash)

# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:13
IceCube::TimeUtil::ICAL_DAYS = T.let(T.unsafe(nil), Hash)

# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:18
IceCube::TimeUtil::MONTHS = T.let(T.unsafe(nil), Hash)

# A utility class for safely moving time around
#
# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:267
class IceCube::TimeUtil::TimeWrapper
  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:268
  def initialize(time, dst_adjust = T.unsafe(nil)); end

  # DST-safely add an interval of time to the wrapped time
  #
  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:286
  def add(type, val); end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:300
  def clear_below(type); end

  # Move to the first of the month, 0 hours
  #
  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:333
  def clear_day; end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:328
  def clear_hour; end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:324
  def clear_min; end

  # Clear to january 1st
  #
  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:338
  def clear_month; end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:320
  def clear_sec; end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:308
  def hour=(value); end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:312
  def min=(value); end

  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:316
  def sec=(value); end

  # Get the wrapped time back in its original zone & format
  #
  # pkg:gem/ice_cube#lib/ice_cube/time_util.rb:279
  def to_time; end
end

# Clear everything below a certain type
#
# pkg:gem/ice_cube#lib/ice_cube/time_util.rb:299
IceCube::TimeUtil::TimeWrapper::CLEAR_ORDER = T.let(T.unsafe(nil), Array)

# An exception for when an until date on a Rule is passed
#
# pkg:gem/ice_cube#lib/ice_cube/errors/until_exceeded.rb:3
class IceCube::UntilExceeded < ::StopIteration; end

# pkg:gem/ice_cube#lib/ice_cube/version.rb:2
IceCube::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:4
class IceCube::ValidatedRule < ::IceCube::Rule
  include ::IceCube::Validations::ScheduleLock
  include ::IceCube::Validations::Count
  include ::IceCube::Validations::Until

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:26
  def initialize(interval = T.unsafe(nil)); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:37
  def base_interval_validation; end

  # Remove the specified base validations
  #
  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:111
  def clobber_base_validations(*types); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:62
  def full_required?; end

  # Compute the next time after (or including) the specified time in respect
  # to the given start time
  #
  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:47
  def next_time(time, start_time, closing_time); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:41
  def other_interval_validations; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:58
  def realign(opening_time, start_time); end

  # Fully replace validations
  #
  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:102
  def replace_validations_for(key, arr); end

  # Reset the uses on the rule to 0
  #
  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:31
  def reset; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:76
  def to_hash; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:86
  def to_ical; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:66
  def to_s; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:24
  def validations; end

  # Get the collection that contains validations of a certain type
  #
  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:97
  def validations_for(key); end

  private

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:131
  def find_acceptable_time_before(boundary); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:125
  def finds_acceptable_time?; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:119
  def normalized_interval(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:169
  def past_closing_time?(closing_time); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:151
  def shift_time_by_validation(res, validation); end

  # Returns true if all validations for the current rule match
  # otherwise false and shifts to the first (largest) unmatched offset
  #
  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:141
  def validation_accepts_or_updates_time?(validations_for_type); end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:173
  def validation_names; end

  # pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:177
  def verify_alignment(value, freq, rule_part); end
end

# Validations ordered for efficiency in sequence of:
# * descending intervals
# * boundary limits
# * base values by cardinality (n = 60, 60, 31, 24, 12, 7)
# * locks by cardinality (n = 365, 60, 60, 31, 24, 12, 7)
# * interval multiplier
#
# pkg:gem/ice_cube#lib/ice_cube/validated_rule.rb:16
IceCube::ValidatedRule::VALIDATION_ORDER = T.let(T.unsafe(nil), Array)

# pkg:gem/ice_cube#lib/ice_cube.rb:38
module IceCube::Validations; end

# pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:2
module IceCube::Validations::Count
  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:8
  def count(max); end

  # Value reader for limit
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:4
  def occurrence_count; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:16
class IceCube::Validations::Count::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:19
  def initialize(count, rule); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:40
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:44
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:17
  def count; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:28
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:17
  def rule; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:24
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/count.rb:32
  def validate(time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:2
module IceCube::Validations::DailyInterval
  # Add a new interval validation
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:4
  def interval(interval); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:15
class IceCube::Validations::DailyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:18
  def initialize(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:42
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:46
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:38
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:26
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:16
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:22
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/daily_interval.rb:30
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:2
module IceCube::Validations::Day
  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:3
  def day(*days); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:19
class IceCube::Validations::Day::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:23
  def initialize(day); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:43
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:47
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:39
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:20
  def day; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:35
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:27
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:31
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day.rb:21
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:2
module IceCube::Validations::DayOfMonth
  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:3
  def day_of_month(*days); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:15
class IceCube::Validations::DayOfMonth::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:19
  def initialize(day); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:39
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:43
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:35
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:16
  def day; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:31
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:23
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:27
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_month.rb:17
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:2
module IceCube::Validations::DayOfWeek
  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:3
  def day_of_week(dows); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:14
class IceCube::Validations::DayOfWeek::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:17
  def initialize(day, occ); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:55
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:61
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:47
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:15
  def day; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:29
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:15
  def occ; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:25
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_week.rb:33
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:2
module IceCube::Validations::DayOfYear
  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:3
  def day_of_year(*days); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:14
class IceCube::Validations::DayOfYear::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:17
  def initialize(day); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:40
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:44
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:15
  def day; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:25
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:21
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/day_of_year.rb:29
  def validate(step_time, start_time); end
end

# This abstract validation class is used by the various "fixed-time" (e.g.
# day, day_of_month, hour_of_day) Validation and ScheduleLock::Validation
# modules. It is not a standalone rule validation module like the others.
#
# Given the including Validation's defined +type+ field, it will lock to the
# specified +value+ or else the corresponding time unit from the schedule's
# start_time
#
# pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:10
class IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:13
  def validate(time, start_time); end

  private

  # pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:83
  def starting_unit(start_time); end

  # For monthly rules that have no specified day value, the validation relies
  # on the schedule start time and jumps to include every month even if it
  # has fewer days than the schedule's start day.
  #
  # Negative day values (from month end) also include all months.
  #
  # Positive day values are taken literally so months with fewer days will
  # be skipped.
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:56
  def validate_day_lock(time, start_time); end

  # Lock the hour if explicitly set by hour_of_day, but allow for the nearest
  # hour during DST start to keep the correct interval.
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:35
  def validate_hour_lock(time, start_time); end

  # Validate if the current time unit matches the same unit from the schedule
  # start time, returning the difference to the interval
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:26
  def validate_interval_lock(time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/fixed_value.rb:11
IceCube::Validations::FixedValue::INTERVALS = T.let(T.unsafe(nil), Hash)

# pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:2
module IceCube::Validations::HourOfDay
  # Add hour of day validations
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:4
  def hour_of_day(*hours); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:18
  def realign(opening_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:34
class IceCube::Validations::HourOfDay::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:38
  def initialize(hour); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:58
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:62
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:54
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:50
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:35
  def hour; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:42
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:46
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hour_of_day.rb:36
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:2
module IceCube::Validations::HourlyInterval
  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:3
  def interval(interval); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:12
class IceCube::Validations::HourlyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:15
  def initialize(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:40
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:44
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:23
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:13
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:19
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/hourly_interval.rb:27
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:2
module IceCube::Validations::MinuteOfHour
  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:3
  def minute_of_hour(*minutes); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:17
  def realign(opening_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:26
class IceCube::Validations::MinuteOfHour::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:30
  def initialize(minute); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:50
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:54
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:46
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:42
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:34
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:27
  def minute; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:38
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minute_of_hour.rb:28
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:2
module IceCube::Validations::MinutelyInterval
  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:3
  def interval(interval); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:12
class IceCube::Validations::MinutelyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:15
  def initialize(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:40
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:44
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:23
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:13
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:19
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/minutely_interval.rb:27
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:2
module IceCube::Validations::MonthOfYear
  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:3
  def month_of_year(*months); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:16
class IceCube::Validations::MonthOfYear::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:20
  def initialize(month); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:40
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:44
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:32
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:24
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:17
  def month; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:28
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/month_of_year.rb:18
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:2
module IceCube::Validations::MonthlyInterval
  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:3
  def interval(interval); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:13
class IceCube::Validations::MonthlyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:16
  def initialize(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:40
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:44
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:24
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:14
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:20
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/monthly_interval.rb:28
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:2
module IceCube::Validations::ScheduleLock
  # Lock the given time units to the units from schedule's +start_time+
  # These locks are all clobberable by other rules of the same #type
  # using +clobber_base_validation+
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:7
  def schedule_lock(*types); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:13
class IceCube::Validations::ScheduleLock::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:16
  def initialize(type); end

  # no -op
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:36
  def build_hash(builder); end

  # no -op
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:40
  def build_ical(builder); end

  # no -op
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:32
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:24
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:20
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:14
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/schedule_lock.rb:14
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:2
module IceCube::Validations::SecondOfMinute
  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:17
  def realign(opening_time, start_time); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:3
  def second_of_minute(*seconds); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:26
class IceCube::Validations::SecondOfMinute::Validation < ::IceCube::Validations::FixedValue
  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:30
  def initialize(second); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:50
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:54
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:46
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:42
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:34
  def key; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:27
  def second; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:38
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/second_of_minute.rb:28
  def value; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:2
module IceCube::Validations::SecondlyInterval
  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:3
  def interval(interval); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:12
class IceCube::Validations::SecondlyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:15
  def initialize(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:37
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:41
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:33
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:23
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:13
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:19
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/secondly_interval.rb:27
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:2
module IceCube::Validations::Until
  extend ::IceCube::Deprecated

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:11
  def until(time); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:9
  def until_date(*args, &block); end

  # Value reader for limit
  #
  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:6
  def until_time; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:16
class IceCube::Validations::Until::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:19
  def initialize(time); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:41
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:45
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:36
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:27
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:17
  def time; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:23
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/until.rb:31
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:2
module IceCube::Validations::WeeklyInterval
  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:3
  def interval(interval, week_start = T.unsafe(nil)); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:11
class IceCube::Validations::WeeklyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:14
  def initialize(interval, week_start); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:42
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:47
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:38
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:23
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:12
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:19
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:27
  def validate(step_time, start_time); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/weekly_interval.rb:12
  def week_start; end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:2
module IceCube::Validations::YearlyInterval
  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:3
  def interval(interval); end
end

# pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:10
class IceCube::Validations::YearlyInterval::Validation
  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:13
  def initialize(interval); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:35
  def build_hash(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:39
  def build_ical(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:31
  def build_s(builder); end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:21
  def dst_adjust?; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:11
  def interval; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:17
  def type; end

  # pkg:gem/ice_cube#lib/ice_cube/validations/yearly_interval.rb:25
  def validate(step_time, start_time); end
end

# pkg:gem/ice_cube#lib/ice_cube/rules/weekly_rule.rb:2
class IceCube::WeeklyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::WeeklyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/weekly_rule.rb:16
  def initialize(interval = T.unsafe(nil), week_start = T.unsafe(nil)); end

  # Move the effective start time to correct for when the schedule has
  # validations earlier in the week than the selected start time, e.g.
  #
  #     Schedule.new(wednesday).weekly(2).day(:monday)
  #
  # The effective start time gets realigned to the second next Monday, jumping
  # over the gap week for the interval (2). Without realignment, the correct
  # Monday occurrence would be missed when the schedule performs a 7-day jump
  # into the next interval week, arriving on the Wednesday. This corrects any
  # selections from dates that are misaligned to the schedule interval.
  #
  # pkg:gem/ice_cube#lib/ice_cube/rules/weekly_rule.rb:34
  def realign(step_time, start_time); end

  # Calculate how many days to the first wday validation in the correct
  # interval week. This may move backwards within the week if starting in an
  # interval week with earlier validations.
  #
  # pkg:gem/ice_cube#lib/ice_cube/rules/weekly_rule.rb:45
  def wday_offset(step_time, start_time); end

  # pkg:gem/ice_cube#lib/ice_cube/rules/weekly_rule.rb:14
  def week_start; end
end

# pkg:gem/ice_cube#lib/ice_cube/parsers/yaml_parser.rb:4
class IceCube::YamlParser < ::IceCube::HashParser
  # pkg:gem/ice_cube#lib/ice_cube/parsers/yaml_parser.rb:9
  def initialize(yaml); end

  # pkg:gem/ice_cube#lib/ice_cube/parsers/yaml_parser.rb:7
  def hash; end
end

# pkg:gem/ice_cube#lib/ice_cube/parsers/yaml_parser.rb:5
IceCube::YamlParser::SERIALIZED_START = T.let(T.unsafe(nil), Regexp)

# pkg:gem/ice_cube#lib/ice_cube/rules/yearly_rule.rb:2
class IceCube::YearlyRule < ::IceCube::ValidatedRule
  include ::IceCube::Validations::HourOfDay
  include ::IceCube::Validations::MinuteOfHour
  include ::IceCube::Validations::SecondOfMinute
  include ::IceCube::Validations::DayOfMonth
  include ::IceCube::Validations::DayOfWeek
  include ::IceCube::Validations::Day
  include ::IceCube::Validations::MonthOfYear
  include ::IceCube::Validations::DayOfYear
  include ::IceCube::Validations::YearlyInterval

  # pkg:gem/ice_cube#lib/ice_cube/rules/yearly_rule.rb:14
  def initialize(interval = T.unsafe(nil)); end
end
