# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `phonelib` gem.
# Please instead update this file by running `bin/tapioca gem phonelib`.


# pkg:gem/phonelib#lib/validators/phone_validator.rb:75
class PhoneValidator < ::ActiveModel::EachValidator
  include ::Phonelib::Core

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:82
  def check_validity!; end

  # Validation method
  #
  # pkg:gem/phonelib#lib/validators/phone_validator.rb:90
  def validate_each(record, attribute, value); end

  private

  # @private
  #
  # pkg:gem/phonelib#lib/validators/phone_validator.rb:225
  def countries; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:149
  def detailed_countries; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:136
  def detailed_error_options(error); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:110
  def detailed_errors?; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:145
  def detailed_types; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:174
  def extensions_allowed?; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:114
  def legacy_error_options; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:106
  def message; end

  # @private
  #
  # pkg:gem/phonelib#lib/validators/phone_validator.rb:211
  def phone_countries(phone); end

  # @private
  #
  # pkg:gem/phonelib#lib/validators/phone_validator.rb:201
  def phone_types(phone); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:155
  def phone_valid?(phone); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:190
  def specified_country(record); end

  # @private
  #
  # pkg:gem/phonelib#lib/validators/phone_validator.rb:217
  def types; end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:164
  def valid_country?(phone); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:169
  def valid_extensions?(phone); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:184
  def valid_input_format?(value); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:178
  def valid_international_prefix?(phone); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:159
  def valid_types?(phone); end

  # pkg:gem/phonelib#lib/validators/phone_validator.rb:118
  def validate_with_details(record, attribute, phone); end
end

# pkg:gem/phonelib#lib/validators/phone_validator.rb:76
PhoneValidator::E164_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/phonelib#lib/validators/phone_validator.rb:77
PhoneValidator::SUPPORTED_FORMATS = T.let(T.unsafe(nil), Array)

# main Phonelib module definition
#
# pkg:gem/phonelib#lib/phonelib.rb:4
module Phonelib
  extend ::Phonelib::Core
end

# main module that includes all basic data and methods
#
# pkg:gem/phonelib#lib/phonelib/core.rb:5
module Phonelib::Core
  # pkg:gem/phonelib#lib/phonelib/core.rb:210
  def add_additional_regex(country, type, national_regex); end

  # pkg:gem/phonelib#lib/phonelib/core.rb:231
  def additional_regexes; end

  # setter for data file to use
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:197
  def additional_regexes=(data); end

  # @private getter for phone data indexed by country code (internal use only)
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:29
  def data_by_country_codes; end

  # getter method for default_country variable
  # @return [String,Symbol,Array<String,Symbol>,nil] Default country ISO2 code or codes used for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:59
  def default_country; end

  # setter method for default_country variable
  # @param country [String,Symbol,Array<String,Symbol>] Default country ISO2 code or codes used for parsing
  # @return [String,Symbol,Array<String,Symbol>] Default country ISO2 code or codes used for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:66
  def default_country=(country); end

  # pkg:gem/phonelib#lib/phonelib/core.rb:219
  def dump_additional_regexes; end

  # eagerly initialize the gem, loads data into memory. not required, initialization is done lazily otherwise, but
  # may be desirable in production enviroments to avoid initialization time on first use.
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:11
  def eager_load!; end

  # getter method for extension_separate_symbols variable
  # @return [String] Default extension separator symbols used for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:91
  def extension_separate_symbols; end

  # setter method for extension_separate_symbols variable
  # @param separator [String] extension separator symbols used for parsing
  # @return [String] Default extension separator symbols used for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:98
  def extension_separate_symbols=(separator); end

  # getter method for extension_separator variable
  # @return [String] Default extension separator used for formatting
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:75
  def extension_separator; end

  # setter method for extension_separator variable
  # @param separator [String] extension separator used for formatting
  # @return [String] Default extension separator used for formatting
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:82
  def extension_separator=(separator); end

  # getter for ignore plus flag
  # @return [Boolean] Flag defines whether to reset country in case number has + and country prefix doesn't match
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:140
  def ignore_plus; end

  # setter for ignore plus flag
  # @param ignore_plus [Boolean] ignore plus sign or not
  # @return [Boolean] Flag defines whether to ignore plus for country reset during validations in case country prefix doesn't match
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:147
  def ignore_plus=(ignore_plus); end

  # method checks if passed phone number is impossible
  # @param phone_number [String] the phone number to be parsed
  # @return [Boolean] phone impossible or not
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:461
  def impossible?(phone_number); end

  # method checks if passed phone number is invalid
  # @param phone_number [String] the phone number to be parsed
  # @return [Boolean] phone invalid or not
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:447
  def invalid?(phone_number); end

  # method checks if passed phone number is invalid for provided country
  # @param phone_number [String] the phone number to be parsed
  # @param country [String] ISO2 country code for phone parsing
  # @return [Boolean] phone invalid for specified country or not
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:477
  def invalid_for_country?(phone_number, country); end

  # pkg:gem/phonelib#lib/phonelib/core.rb:191
  def override_phone_data; end

  # setter for data file to use
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:185
  def override_phone_data=(file_path); end

  # method for parsing phone number.
  # On first run fills @@phone_data with data present in yaml file
  # @param phone [String] the phone number to be parsed
  # @param passed_country [nil|String|Symbol] country for phone parsing
  # @return [Phonelib::Phone] parsed phone entity
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:433
  def parse(phone, passed_country = T.unsafe(nil)); end

  # getter for flag for special phone types parsing
  # @return [Boolean] Flag defines whether to parse special phone types
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:108
  def parse_special; end

  # setter for flag for special phone types parsing
  # @param special [Boolean] parse special phone types value
  # @return [Boolean] Flag defines whether to parse special phone types
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:115
  def parse_special=(special); end

  # getter for phone data for other modules of gem, can be used outside
  # @return [Hash] all data for phone parsing
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:24
  def phone_data; end

  # @private getter for all international prefixes in phone_data
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:34
  def phone_data_int_prefixes; end

  # @private getter for extended phone data
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:50
  def phone_ext_data; end

  # @private getter for phone regexp cache (internal use only)
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:42
  def phone_regexp_cache; end

  # method checks if passed phone number is possible
  # @param phone_number [String] the phone number to be parsed
  # @return [Boolean] phone possible or not
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:454
  def possible?(phone_number); end

  # getter for sanitize regex
  # @return [String] regex of symbols to wipe from parsed number
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:156
  def sanitize_regex; end

  # setter for sanitize regex
  # @param regex [String] symbols to wipe from parsed number
  # @return [String] regex of symbols to wipe from parsed number
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:163
  def sanitize_regex=(regex); end

  # pkg:gem/phonelib#lib/phonelib/core.rb:18
  def skip_eager_loading!; end

  # getter for strict check flag
  # @return [Boolean] Flag defines whether to do strict parsing check
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:124
  def strict_check; end

  # setter for strict check flag
  # @param strict [Boolean] make a strict parsing or not
  # @return [Boolean] Flag defines whether to do strict parsing check
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:131
  def strict_check=(strict); end

  # getter for strict double prefix check flag
  # @return [Boolean] Flag defines whether to do strict double prefix parsing check
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:172
  def strict_double_prefix_check; end

  # setter for strict double prefix check flag
  # @param strict [Boolean] make a strict double prefix parsing or not
  # @return [Boolean] Flag defines whether to do strict double prefix parsing check
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:179
  def strict_double_prefix_check=(strict); end

  # method checks if passed phone number is valid
  # @param phone_number [String] the phone number to be parsed
  # @return [Boolean] phone valid or not
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:440
  def valid?(phone_number); end

  # method checks if passed phone number is valid for provided country
  # @param phone_number [String] the phone number to be parsed
  # @param country [String] ISO2 country code for phone parsing
  # @return [Boolean] phone valid for specified country or not
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:469
  def valid_for_country?(phone_number, country); end

  # pkg:gem/phonelib#lib/phonelib/core.rb:241
  def vanity_conversion; end

  # setter for vanity phone numbers chars replacement
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:237
  def vanity_conversion=(value); end

  private

  # @private Load data file into memory
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:484
  def load_data; end

  # @private Load extended data file into memory
  #
  # pkg:gem/phonelib#lib/phonelib/core.rb:510
  def load_ext_data; end
end

# @private Area code countries for mobile type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:354
Phonelib::Core::AREA_CODE_MOBILE_COUNTRIES = T.let(T.unsafe(nil), Array)

# @private Area code mobile phone token
#
# pkg:gem/phonelib#lib/phonelib/core.rb:357
Phonelib::Core::AREA_CODE_MOBILE_TOKENS = T.let(T.unsafe(nil), Hash)

# @private area code optional type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:306
Phonelib::Core::AREA_CODE_OPTIONAL = T.let(T.unsafe(nil), Symbol)

# @private Area code possible types
#
# pkg:gem/phonelib#lib/phonelib/core.rb:351
Phonelib::Core::AREA_CODE_TYPES = T.let(T.unsafe(nil), Array)

# @private carrier selection codes
#
# pkg:gem/phonelib#lib/phonelib/core.rb:304
Phonelib::Core::CARRIER_SELECTION_CODES = T.let(T.unsafe(nil), Symbol)

# @private carrier services type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:298
Phonelib::Core::CARRIER_SERVICES = T.let(T.unsafe(nil), Symbol)

# @private carrier specific type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:290
Phonelib::Core::CARRIER_SPECIFIC = T.let(T.unsafe(nil), Symbol)

# @private Country code key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:326
Phonelib::Core::COUNTRY_CODE = T.let(T.unsafe(nil), Symbol)

# @private Default number formatting data hash
#
# pkg:gem/phonelib#lib/phonelib/core.rb:363
Phonelib::Core::DEFAULT_NUMBER_FORMAT = T.let(T.unsafe(nil), Hash)

# @private directory services
#
# pkg:gem/phonelib#lib/phonelib/core.rb:300
Phonelib::Core::DIRECTORY_SERVICES = T.let(T.unsafe(nil), Symbol)

# @private Double country prefix flag key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:334
Phonelib::Core::DOUBLE_COUNTRY_PREFIX_FLAG = T.let(T.unsafe(nil), Symbol)

# @private emergency numbers
#
# pkg:gem/phonelib#lib/phonelib/core.rb:288
Phonelib::Core::EMERGENCY = T.let(T.unsafe(nil), Symbol)

# @private expanded emergency type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:294
Phonelib::Core::EXPANDED_EMERGENCY = T.let(T.unsafe(nil), Symbol)

# @private Extended data carriers array key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:413
Phonelib::Core::EXT_CARRIERS = T.let(T.unsafe(nil), Symbol)

# @private Extended data key for carrier in prefixes hash
#
# pkg:gem/phonelib#lib/phonelib/core.rb:419
Phonelib::Core::EXT_CARRIER_KEY = T.let(T.unsafe(nil), Symbol)

# @private Extended data country names array key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:409
Phonelib::Core::EXT_COUNTRY_NAMES = T.let(T.unsafe(nil), Symbol)

# @private Extended data geo names array key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:407
Phonelib::Core::EXT_GEO_NAMES = T.let(T.unsafe(nil), Symbol)

# @private Extended data key for geoname in prefixes hash
#
# pkg:gem/phonelib#lib/phonelib/core.rb:415
Phonelib::Core::EXT_GEO_NAME_KEY = T.let(T.unsafe(nil), Symbol)

# @private Extended data prefixes hash key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:405
Phonelib::Core::EXT_PREFIXES = T.let(T.unsafe(nil), Symbol)

# @private Extended data timezones array key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:411
Phonelib::Core::EXT_TIMEZONES = T.let(T.unsafe(nil), Symbol)

# @private Extended data key for timezone in prefixes hash
#
# pkg:gem/phonelib#lib/phonelib/core.rb:417
Phonelib::Core::EXT_TIMEZONE_KEY = T.let(T.unsafe(nil), Symbol)

# @private Extended data file
#
# pkg:gem/phonelib#lib/phonelib/core.rb:250
Phonelib::Core::FILE_EXT_DATA = T.let(T.unsafe(nil), String)

# @private Main data file
#
# pkg:gem/phonelib#lib/phonelib/core.rb:248
Phonelib::Core::FILE_MAIN_DATA = T.let(T.unsafe(nil), String)

# @private Fixed line pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:279
Phonelib::Core::FIXED_LINE = T.let(T.unsafe(nil), Symbol)

# pkg:gem/phonelib#lib/phonelib/core.rb:423
Phonelib::Core::FIXED_LINE_OR_MOBILE_ARRAY = T.let(T.unsafe(nil), Array)

# @private In case MOBILE and FIXED patterns are the same,
#   this type is returned
#
# pkg:gem/phonelib#lib/phonelib/core.rb:284
Phonelib::Core::FIXED_OR_MOBILE = T.let(T.unsafe(nil), Symbol)

# @private Static arrays used to avoid allocations
#
# pkg:gem/phonelib#lib/phonelib/core.rb:422
Phonelib::Core::FIXED_OR_MOBILE_ARRAY = T.let(T.unsafe(nil), Array)

# @private Formats key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:338
Phonelib::Core::FORMATS = T.let(T.unsafe(nil), Symbol)

# Validation patterns keys constants
# @private General pattern for country key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:256
Phonelib::Core::GENERAL = T.let(T.unsafe(nil), Symbol)

# @private International prefix key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:330
Phonelib::Core::INTERNATIONAL_PREFIX = T.let(T.unsafe(nil), Symbol)

# @private Leading digits key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:328
Phonelib::Core::LEADING_DIGITS = T.let(T.unsafe(nil), Symbol)

# @private Main country for code key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:332
Phonelib::Core::MAIN_COUNTRY_FOR_CODE = T.let(T.unsafe(nil), Symbol)

# @private Mobile phone number pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:281
Phonelib::Core::MOBILE = T.let(T.unsafe(nil), Symbol)

# @private National prefix key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:318
Phonelib::Core::NATIONAL_PREFIX = T.let(T.unsafe(nil), Symbol)

# @private National prefix for parsing key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:320
Phonelib::Core::NATIONAL_PREFIX_FOR_PARSING = T.let(T.unsafe(nil), Symbol)

# @private National prefix rule key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:324
Phonelib::Core::NATIONAL_PREFIX_RULE = T.let(T.unsafe(nil), Symbol)

# @private National prefix transform rule key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:322
Phonelib::Core::NATIONAL_PREFIX_TRANSFORM_RULE = T.let(T.unsafe(nil), Symbol)

# pkg:gem/phonelib#lib/phonelib/core.rb:426
Phonelib::Core::NIL_RESULT_ARRAY = T.let(T.unsafe(nil), Array)

# @private no international dialling type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:296
Phonelib::Core::NO_INTERNATIONAL_DIALING = T.let(T.unsafe(nil), Symbol)

# @private Pager phone number pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:271
Phonelib::Core::PAGER = T.let(T.unsafe(nil), Symbol)

# @private Pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:340
Phonelib::Core::PATTERN = T.let(T.unsafe(nil), Symbol)

# @private A personal number is associated with a particular person,
# and may be routed to either a MOBILE or FIXED_LINE number.
#
# pkg:gem/phonelib#lib/phonelib/core.rb:269
Phonelib::Core::PERSONAL_NUMBER = T.let(T.unsafe(nil), Symbol)

# @private Plus sign
#
# pkg:gem/phonelib#lib/phonelib/core.rb:345
Phonelib::Core::PLUS_SIGN = T.let(T.unsafe(nil), String)

# @private Possible national number lengths imported from libphonenumber
#
# pkg:gem/phonelib#lib/phonelib/core.rb:314
Phonelib::Core::POSSIBLE_LENGTHS = T.let(T.unsafe(nil), Symbol)

# @private Possible local-only number lengths imported from libphonenumber
#
# pkg:gem/phonelib#lib/phonelib/core.rb:316
Phonelib::Core::POSSIBLE_LOCAL_ONLY_LENGTHS = T.let(T.unsafe(nil), Symbol)

# @private Possible regex pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:312
Phonelib::Core::POSSIBLE_PATTERN = T.let(T.unsafe(nil), Symbol)

# pkg:gem/phonelib#lib/phonelib/core.rb:424
Phonelib::Core::POSSIBLE_VALID_ARRAY = T.let(T.unsafe(nil), Array)

# @private Freephone line pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:258
Phonelib::Core::PREMIUM_RATE = T.let(T.unsafe(nil), Symbol)

# @private Shared cost pattern key. The cost of this call is shared
# between caller and recipient, and is hence typically less than
# PREMIUM_RATE calls
#
# pkg:gem/phonelib#lib/phonelib/core.rb:264
Phonelib::Core::SHARED_COST = T.let(T.unsafe(nil), Symbol)

# @private Short key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:342
Phonelib::Core::SHORT = T.let(T.unsafe(nil), Symbol)

# @private Short code
#
# pkg:gem/phonelib#lib/phonelib/core.rb:286
Phonelib::Core::SHORT_CODE = T.let(T.unsafe(nil), Symbol)

# @private short codes types keys
#
# pkg:gem/phonelib#lib/phonelib/core.rb:397
Phonelib::Core::SHORT_CODES = T.let(T.unsafe(nil), Array)

# @private SMS Services only type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:292
Phonelib::Core::SMS_SERVICES = T.let(T.unsafe(nil), Symbol)

# @private standard rate type
#
# pkg:gem/phonelib#lib/phonelib/core.rb:302
Phonelib::Core::STANDARD_RATE = T.let(T.unsafe(nil), Symbol)

# @private Freephone line pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:260
Phonelib::Core::TOLL_FREE = T.let(T.unsafe(nil), Symbol)

# @private Types key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:336
Phonelib::Core::TYPES = T.let(T.unsafe(nil), Symbol)

# @private hash of all phone types with human representation
#
# pkg:gem/phonelib#lib/phonelib/core.rb:369
Phonelib::Core::TYPES_DESC = T.let(T.unsafe(nil), Hash)

# pkg:gem/phonelib#lib/phonelib/core.rb:394
Phonelib::Core::TYPES_DESC_KEYS = T.let(T.unsafe(nil), Array)

# @private Used for 'Universal Access Numbers' or 'Company Numbers'.
#   They may be further routed to specific offices, but allow one number
#   to be used for a company.
#
# pkg:gem/phonelib#lib/phonelib/core.rb:275
Phonelib::Core::UAN = T.let(T.unsafe(nil), Symbol)

# Internal use keys for validations
# @private Valid regex pattern key
#
# pkg:gem/phonelib#lib/phonelib/core.rb:310
Phonelib::Core::VALID_PATTERN = T.let(T.unsafe(nil), Symbol)

# pkg:gem/phonelib#lib/phonelib/core.rb:425
Phonelib::Core::VALID_POSSIBLE_ARRAY = T.let(T.unsafe(nil), Array)

# @private vanity numbers 4 keys letters
#
# pkg:gem/phonelib#lib/phonelib/core.rb:348
Phonelib::Core::VANITY_4_LETTERS_KEYS_REGEX = T.let(T.unsafe(nil), Regexp)

# @private Used for 'Voice Mail Access Numbers'.
#
# pkg:gem/phonelib#lib/phonelib/core.rb:277
Phonelib::Core::VOICEMAIL = T.let(T.unsafe(nil), Symbol)

# @private VoIP pattern key. This includes TSoIP (Telephony Service over IP)
#
# pkg:gem/phonelib#lib/phonelib/core.rb:266
Phonelib::Core::VOIP = T.let(T.unsafe(nil), Symbol)

# Read-only collection of phone validation errors.
#
# pkg:gem/phonelib#lib/phonelib/errors.rb:5
class Phonelib::Errors
  include ::Enumerable

  # pkg:gem/phonelib#lib/phonelib/errors.rb:8
  def initialize(errors = T.unsafe(nil)); end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:29
  def details; end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:13
  def each(&block); end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:17
  def empty?; end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:25
  def first; end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:38
  def full_messages(options = T.unsafe(nil)); end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:33
  def messages(options = T.unsafe(nil)); end

  # pkg:gem/phonelib#lib/phonelib/errors.rb:21
  def size; end
end

# class for parsed phone number, includes validation and formatting methods
#
# pkg:gem/phonelib#lib/phonelib/phone.rb:5
class Phonelib::Phone
  include ::Phonelib::PhoneAnalyzerHelper
  include ::Phonelib::PhoneAnalyzer
  include ::Phonelib::PhoneExtendedData
  include ::Phonelib::PhoneFormatter
  include ::Phonelib::PhoneValidation

  # class initialization method
  # @param phone [String] Phone number for parsing
  # @param country [String|Symbol] Country specification for parsing.
  #   Must be ISO code of country (2 letters) like 'US', 'us' or :us
  #   for United States
  # @return [Phonelib::Phone] parsed phone instance
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:28
  def initialize(phone, country = T.unsafe(nil)); end

  # Compare a phone number against a string or other parsed number
  # @param other [String|Phonelib::Phone] Phone number to compare against
  # @return [Boolean] result of equality comparison
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:54
  def ==(other); end

  # Returns all countries that matched valid patterns
  # @return [Array] Possible ISO2 country codes array
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:108
  def countries; end

  # Returns first country that matched valid patterns
  # @return [String] valid country ISO2 code or first matched country code
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:130
  def country; end

  # Returns whether the original input begins with an explicit + or 00
  # international prefix after parser-recognized leading formatting.
  # @return [Boolean] original input has an explicit international prefix
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:72
  def explicit_international_prefix?; end

  # @!attribute [r] extension
  # @return [String] phone extension passed for parsing after a number
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:11
  def extension; end

  # Return human representation of phone type
  # @return [String] Human readable valid phone type
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:102
  def human_type; end

  # Returns human representation of all matched phone types
  # @return [Array] Array of human readable valid phone types
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:96
  def human_types; end

  # Returns whether a current parsed phone number is impossible
  # @return [Boolean] parsed phone is impossible
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:160
  def impossible?; end

  # Returns whether a current parsed phone number is invalid
  # @return [Boolean] parsed phone is invalid
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:146
  def invalid?; end

  # Returns whether a current parsed phone number is invalid for specified
  # country
  # @param country [String|Symbol] ISO code of country (2 letters) like 'US',
  #   'us' or :us for United States
  # @return [Boolean] parsed phone number is invalid
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:196
  def invalid_for_country?(country); end

  # returns local number
  # @return [String] local number
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:166
  def local_number; end

  # @!attribute [r] national_number
  # @return [String] phone national number
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:14
  def national_number; end

  # @!attribute [r] original
  # @return [String] original phone number passed for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:8
  def original; end

  # Returns whether a current parsed phone number is possible
  # @return [Boolean] parsed phone is possible
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:152
  def possible?; end

  # Returns all possible types that matched possible patterns
  # @return [Array] all possible phone types
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:84
  def possible_types; end

  # method to get sanitized phone number (only numbers)
  # @return [String] Sanitized phone number
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:62
  def sanitized; end

  # method returns string representation of parsed phone
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:47
  def to_s; end

  # Returns first phone type that matched
  # @return [Symbol] valid phone type
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:90
  def type; end

  # Returns all phone types that matched valid patterns
  # @return [Array] all valid phone types
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:78
  def types; end

  # Returns whether a current parsed phone number is valid
  # @return [Boolean] parsed phone is valid
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:138
  def valid?; end

  # Return countries with valid patterns
  # @return [Array] Valid ISO2 country codes array
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:114
  def valid_countries; end

  # Return valid country
  # @return [String] valid ISO2 country code
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:122
  def valid_country; end

  # Returns whether a current parsed phone number is valid for specified
  # country
  # @param country [String|Symbol] ISO code of country (2 letters) like 'US',
  #   'us' or :us for United States
  # @return [Boolean] parsed phone number is valid
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:183
  def valid_for_country?(country); end

  private

  # @private analyzing results of the country that #country resolved to.
  # Every value derived from a single country (national number, format,
  # national prefix) must be read through here so they cannot disagree.
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:205
  def country_data; end

  # @private get main country for code among provided countries
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:223
  def main_country(countries_array); end

  # @private extracts extension from passed phone number if provided
  #
  # pkg:gem/phonelib#lib/phonelib/phone.rb:210
  def separate_extension(original); end
end

# @private phone analyzing methods module
#
# pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:5
module Phonelib::PhoneAnalyzer
  include ::Phonelib::PhoneAnalyzerHelper

  # parses provided phone if it is valid for  country data and
  # returns result of analyze
  #
  # ==== Attributes
  #
  # * +phone+ - Phone number for parsing
  # * +passed_country+ - Country provided for parsing. Must be ISO code of
  #   country (2 letters) like 'US', 'us' or :us for United States
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:20
  def analyze(phone, passed_country); end

  private

  # Returns all valid and possible phone number types for currently parsed
  # phone for provided data hash.
  #
  # ==== Attributes
  #
  # * +phone+ - phone number for parsing
  # * +data+  - country data
  # * +not_valid+ - specifies that number is not valid by general desc pattern
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:213
  def all_number_types(phone, data, not_valid = T.unsafe(nil)); end

  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:44
  def analyze_single_country(phone, country, passed_country); end

  # method checks which result is better to return
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:60
  def better_result(base_result, result = T.unsafe(nil)); end

  # Create phone representation in e164 format
  #
  # ==== Attributes
  #
  # * +phone+ - phone number for parsing
  # * +data+  - country data to be based on for creating e164 representation
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:169
  def convert_to_e164(phone, data); end

  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:155
  def country_code_candidates_for(phone); end

  # method tries to detect what is the country for provided phone
  #
  # ==== Attributes
  #
  # * +phone+ - phone number for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:134
  def detect_and_parse(phone, country); end

  # Returns possible and valid patterns for validation for provided type
  #
  # ==== Attributes
  #
  # * +all_patterns+ - hash of all patterns for validation
  # * +type+ - type of phone to get patterns for
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:248
  def get_patterns(all_patterns, type); end

  # returns national number and analyzing results for provided phone number
  #
  # ==== Attributes
  #
  # * +data+ - country data
  # * +country_match+ - result of match of phone within full regex
  # * +not_valid+ - specifies that number is not valid by general desc pattern
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:190
  def national_and_data(data, country_match, not_valid = T.unsafe(nil)); end

  # Gets matched number formatting rule or default one
  #
  # ==== Attributes
  #
  # * +national+ - national phone number
  # * +format_data+  - formatting data from country data
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:234
  def number_format(national, format_data); end

  # trying to parse phone for single country including international prefix
  # check for provided country
  #
  # ==== Attributes
  #
  # * +phone+ - phone for parsing
  # * +country+ - country to parse phone with
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:97
  def parse_country(phone, country); end

  # method checks if phone is valid against single provided country data
  #
  # ==== Attributes
  #
  # * +e164+ - e164 representation of phone for parsing
  # * +data+ - country data for single country for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:119
  def parse_single_country(e164, data); end

  # pick best result when several countries specified
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:35
  def pick_results(results); end

  # replacing national prefix to simplified format
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:72
  def with_replaced_national_prefix(passed_phone, data); end
end

# array of types not included for validation check in cycle
#
# pkg:gem/phonelib#lib/phonelib/phone_analyzer.rb:10
Phonelib::PhoneAnalyzer::NOT_FOR_CHECK = T.let(T.unsafe(nil), Array)

# @private helper methods for analyser
#
# pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:5
module Phonelib::PhoneAnalyzerHelper
  private

  # changes phone to with/without double country prefix
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:70
  def changed_dp_phone(country, phone); end

  # defines whether country can have double country prefix in number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:62
  def country_can_dp?(country); end

  # Get country that was provided or default country in needable format
  #
  # ==== Attributes
  #
  # * +country+ - country passed for parsing
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:116
  def country_or_default_country(country); end

  # returns country prefix for provided country or nil
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:50
  def country_prefix(country); end

  # caches regular expression, reusing it for later lookups
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:57
  def cr(regexp); end

  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:8
  def decorate_analyze_result(result); end

  # checks if country can have numbers with double country prefixes
  #
  # ==== Attributes
  #
  # * +data+ - country data used for parsing
  # * +phone+ - phone number being parsed
  # * +parsed+ - parsed regex match for phone
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:90
  def double_prefix_allowed?(data, phone, parsed = T.unsafe(nil)); end

  # Checks if fixed line pattern and mobile pattern are the same and returns
  # appropriate keys
  #
  # ==== Attributes
  #
  # * +data+  - country data
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:200
  def fixed_and_mobile_keys(data); end

  # constructs full regex for phone validation for provided phone data
  # (international prefix, country code, national prefix, valid number)
  #
  # ==== Attributes
  #
  # * +data+ - country data hash
  # * +country_optional+ - whether to put country code as optional group
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:133
  def full_regex_for_data(data, type, country_optional = T.unsafe(nil)); end

  # normalization for passed country unless we are not talking about International XXX
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:237
  def normalize_passed_country(country); end

  # Checks number against regex and compares match length
  #
  # ==== Attributes
  #
  # * +number+ - phone number for validation
  # * +regex+ - regex for perfoming a validation
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:231
  def number_match?(number, regex); end

  # Checks if passed number matches valid and possible patterns
  #
  # ==== Attributes
  #
  # * +number+ - phone number for validation
  # * +p_regex+ - possible regex pattern for validation
  # * +v_regex+ - valid regex pattern for validation
  # * +not_valid+ - specifies that number is not valid by general desc pattern
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:216
  def number_valid_and_possible?(number, p_regex, v_regex, not_valid = T.unsafe(nil)); end

  # Returns original number passed if it's a string or empty string otherwise
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:98
  def original_s; end

  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:19
  def original_starts_with_plus_or_double_zero?; end

  # defines if to validate against single country or not
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:38
  def passed_country(country); end

  # Check if phone match country data
  #
  # ==== Attributes
  #
  # * +phone+ - phone number for parsing
  # * +data+  - country data
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:165
  def phone_match_data?(phone, data, possible = T.unsafe(nil)); end

  # checks if types has both :mobile and :fixed_line and replaces it with
  # :fixed_or_mobile in case both present
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:174
  def sanitize_fixed_mobile(types); end

  # Returns original number without the leading characters that libphonenumber
  # drops in extractPossibleNumber, so a plus or 00 written behind punctuation
  # like "(+501) 623-6848" is still recognized as leading. Vanity conversion
  # runs first, the same way +sanitized+ applies it, so leading letters that
  # convert to significant digits are not stripped as junk.
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:107
  def significant_original_s; end

  # Returns regex for type with special types if needed
  #
  # ==== Attributes
  #
  # * +data+ - country types data for single type
  # * +type+ - possible or valid regex type needed
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:151
  def type_regex(data, type); end

  # returns array of phone types for check for current country data
  #
  # ==== Attributes
  #
  # * +data+  - country data hash
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:188
  def types_for_check(data); end

  # converts symbols in phone to numbers
  #
  # pkg:gem/phonelib#lib/phonelib/phone_analyzer_helper.rb:24
  def vanity_converted(phone); end
end

# module provides extended data methods for parsed phone
#
# pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:5
module Phonelib::PhoneExtendedData
  # Returns carrier of parsed phone number or nil if number is invalid or
  # there is no carrier specified in db for this number
  # @return [String|nil] carrier for parsed phone
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:39
  def carrier; end

  # Returns geo name of parsed phone number or nil if number is invalid or
  # there is no geo name specified in db for this number
  # @return [String|nil] geo name for parsed phone
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:16
  def geo_name; end

  # Returns first timezone (in case several match) of parsed phone number or nil
  # if number is invalid or there is no timezone specified in db for this number
  # @return [String|nil] timezone for parsed phone
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:24
  def timezone; end

  # Returns timezones of parsed phone number or nil if number is invalid or
  # there is no timezone specified in db for this number
  # @return [Array] timezones for parsed phone
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:31
  def timezones; end

  # returns valid country name
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:45
  def valid_country_name; end

  private

  # @private default extended data
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:87
  def default_ext_data; end

  # @private returns extended data ids for current number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:67
  def ext_data; end

  # @private get name from extended phone data by keys
  #
  # ==== Attributes
  #
  # * +name_key+ - names array key from extended data hash
  # * +id_key+   - parameter id key in resolved extended data for number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:60
  def get_ext_name(names_key, id_key); end
end

# @private keys for extended data
#
# pkg:gem/phonelib#lib/phonelib/phone_extended_data.rb:7
Phonelib::PhoneExtendedData::EXT_KEYS = T.let(T.unsafe(nil), Array)

# module includes all formatting methods
#
# pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:5
module Phonelib::PhoneFormatter
  # returns area code of parsed number
  # @return [String|nil] parsed phone area code if available
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:100
  def area_code; end

  # Returns the country code from the original phone number.
  # @return [String] matched country phone code
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:36
  def country_code; end

  # Returns e164 unformatted phone number
  # @param prefix [String] prefix to be placed before the number, "+" by default
  # @return [String] phone formatted in E164 format
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:93
  def e164(prefix = T.unsafe(nil)); end

  # returns e164 format of phone with extension added
  # @param prefix [String] prefix to be placed before the number, "+" by default
  # @return [String] phone formatted in E164 format with extension
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:86
  def full_e164(prefix = T.unsafe(nil)); end

  # returns international formatted number with extension added
  # @param prefix [String] prefix to be placed before the number, "+" by default
  # @return [String] formatted internation phone number with extension
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:79
  def full_international(prefix = T.unsafe(nil)); end

  # returns national formatted number with extension added
  # @return [String] formatted national number with extension
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:72
  def full_national; end

  # Returns e164 formatted phone number. Method can receive single string parameter that will be defined as prefix
  # @param formatted [Boolean] whether to return numbers only or formatted
  # @param prefix [String] prefix to be placed before the number, "+" by default
  # @return [String] formatted international number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:54
  def international(formatted = T.unsafe(nil), prefix = T.unsafe(nil)); end

  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:112
  def method_missing(method, *args); end

  # Returns formatted national number
  # @param formatted [Boolean] whether to return numbers only or formatted
  # @return [String] formatted national number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:9
  def national(formatted = T.unsafe(nil)); end

  # Returns the raw national number that was defined during parsing
  # @return [String] raw national number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:23
  def raw_national; end

  private

  # @private defines if phone can have area code
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:128
  def area_code_possible?; end

  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:123
  def data_country_code; end

  # @private returns extension with separator defined
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:141
  def formatted_extension; end

  # @private Get needable data for formatting phone as national number
  #
  # pkg:gem/phonelib#lib/phonelib/phone_formatter.rb:148
  def formatting_data; end
end

# Framework-independent diagnostics and policy validation for a parsed phone.
#
# pkg:gem/phonelib#lib/phonelib/phone_validation.rb:5
module Phonelib::PhoneValidation
  # Convenience accessor for validation diagnostics.
  # @param options [Hash] phone validation rules
  # @return [Phonelib::Errors]
  #
  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:31
  def errors(options = T.unsafe(nil)); end

  # Returns an immutable result explaining whether this phone satisfies the
  # requested rules and, when it does not, why.
  # @param options [Hash] phone validation rules
  # @return [Phonelib::ValidationResult]
  #
  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:16
  def validation(options = T.unsafe(nil)); end

  private

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:204
  def additional_regex_possible?(national_digits, data); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:287
  def country_calling_code_for(digits); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:281
  def diagnostic_countries; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:214
  def diagnostic_number_context; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:181
  def diagnostic_possibility; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:270
  def digits_after_international_dialing_prefix; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:245
  def international_digits_for_diagnostics; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:90
  def intrinsic_diagnostic_error; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:74
  def intrinsic_validation_errors(possible, possibility); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:334
  def normalize_validation_values(value); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:127
  def parser_national_length; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:135
  def passed_country_invalid?; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:293
  def policy_validation_errors(options, possible); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:157
  def possibility_length_error; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:254
  def possible_lengths_for(data); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:265
  def possible_local_only_lengths_for(data); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:327
  def possible_policy_countries; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:200
  def possible_special_number?; end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:144
  def short_national_number_error(international_digits); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:49
  def validate_boolean_option!(name, value); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:55
  def validate_collection_option!(name, value); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:37
  def validate_options!(options); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:69
  def validate_type_names!(values); end

  # pkg:gem/phonelib#lib/phonelib/phone_validation.rb:119
  def viable_input?; end
end

# pkg:gem/phonelib#lib/phonelib/phone_validation.rb:8
Phonelib::PhoneValidation::MAX_VALIDATION_VALUES = T.let(T.unsafe(nil), Integer)

# pkg:gem/phonelib#lib/phonelib/phone_validation.rb:6
Phonelib::PhoneValidation::VALIDATION_OPTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/phonelib#lib/phonelib/phone_validation.rb:7
Phonelib::PhoneValidation::VALID_TYPE_NAMES = T.let(T.unsafe(nil), Array)

# pkg:gem/phonelib#lib/phonelib/railtie.rb:4
class Phonelib::Railtie < ::Rails::Railtie; end

# A framework-independent, immutable phone validation diagnostic.
#
# pkg:gem/phonelib#lib/phonelib/validation_error.rb:5
class Phonelib::ValidationError
  # pkg:gem/phonelib#lib/phonelib/validation_error.rb:21
  def initialize(code, details = T.unsafe(nil)); end

  # pkg:gem/phonelib#lib/phonelib/validation_error.rb:19
  def code; end

  # pkg:gem/phonelib#lib/phonelib/validation_error.rb:19
  def details; end

  # pkg:gem/phonelib#lib/phonelib/validation_error.rb:30
  def i18n_key; end

  # pkg:gem/phonelib#lib/phonelib/validation_error.rb:34
  def message(translator = T.unsafe(nil)); end

  private

  # pkg:gem/phonelib#lib/phonelib/validation_error.rb:43
  def immutable_copy(value); end
end

# pkg:gem/phonelib#lib/phonelib/validation_error.rb:6
Phonelib::ValidationError::DEFAULT_MESSAGES = T.let(T.unsafe(nil), Hash)

# Immutable outcome of validating a parsed phone against a rule set.
#
# pkg:gem/phonelib#lib/phonelib/validation_result.rb:5
class Phonelib::ValidationResult
  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:8
  def initialize(phone, errors, possibility); end

  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:23
  def error; end

  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:6
  def errors; end

  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:19
  def invalid?; end

  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:6
  def phone; end

  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:6
  def possibility; end

  # pkg:gem/phonelib#lib/phonelib/validation_result.rb:15
  def valid?; end
end
