# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pusher-signature` gem.
# Please instead update this file by running `bin/tapioca gem pusher-signature`.


# pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:1
module Pusher; end

# pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:2
module Pusher::Signature; end

# pkg:gem/pusher-signature#lib/pusher/signature.rb:7
class Pusher::Signature::AuthenticationError < ::RuntimeError; end

# Query string encoding extracted with thanks from em-http-request
#
# pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:4
module Pusher::Signature::QueryEncoder
  class << self
    # URL encodes query parameters:
    # single k=v, or a URL encoded array, if v is an array of values
    #
    # pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:8
    def encode_param(k, v); end

    # Like encode_param, but doesn't url escape keys or values
    #
    # pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:17
    def encode_param_without_escaping(k, v); end

    private

    # pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:38
    def bytesize(string); end

    # pkg:gem/pusher-signature#lib/pusher/signature/query_encoder.rb:27
    def escape(s); end
  end
end

# pkg:gem/pusher-signature#lib/pusher/signature.rb:21
class Pusher::Signature::Request
  include ::Pusher::Signature::QueryEncoder

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:29
  def initialize(method, path, query); end

  # Expose the authentication parameters for a signed request
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:159
  def auth_hash; end

  # Authenticate a request
  #
  # Takes a block which will be called with the auth_key from the request,
  # and which should return a Signature::Token (or nil if no token can be
  # found for the key)
  #
  # Raises errors in the same way as authenticate_by_token!
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:106
  def authenticate(timestamp_grace = T.unsafe(nil)); end

  # Authenticate a request asynchronously
  #
  # This method is useful it you're running a server inside eventmachine and
  # need to lookup the token asynchronously.
  #
  # The block is passed an auth key and a deferrable which should succeed
  # with the token, or fail if the token cannot be found
  #
  # This method returns a deferrable which succeeds with the valid token, or
  # fails with an AuthenticationError which can be used to pass the error
  # back to the user
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:130
  def authenticate_async(timestamp_grace = T.unsafe(nil)); end

  # Authenticate the request with a token, but rather than raising an
  # exception if the request is invalid, simply returns false
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:92
  def authenticate_by_token(token, timestamp_grace = T.unsafe(nil)); end

  # Authenticates the request with a token
  #
  # Raises an AuthenticationError if the request is invalid.
  # AuthenticationError exception messages are designed to be exposed to API
  # consumers, and should help them correct errors generating signatures
  #
  # Timestamp: Unless timestamp_grace is set to nil (which allows this check
  # to be skipped), AuthenticationError will be raised if the timestamp is
  # missing or further than timestamp_grace period away from the real time
  # (defaults to 10 minutes)
  #
  # Signature: Raises AuthenticationError if the signature does not match
  # the computed HMAC. The error contains a hint for how to sign.
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:75
  def authenticate_by_token!(token, timestamp_grace = T.unsafe(nil)); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:22
  def path; end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:22
  def path=(_arg0); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:22
  def query_hash; end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:22
  def query_hash=(_arg0); end

  # Sign the request with the given token, and return the computed
  # authentication parameters
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:48
  def sign(token); end

  # Query parameters merged with the computed authentication parameters
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:166
  def signed_params; end

  private

  # Constant time string comparison
  #
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:226
  def identical?(a, b); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:181
  def parameter_string; end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:172
  def signature(token); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:177
  def string_to_sign; end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:216
  def validate_signature!(token); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:201
  def validate_timestamp!(grace); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:195
  def validate_version!; end
end

# http://www.w3.org/TR/NOTE-datetime
#
# pkg:gem/pusher-signature#lib/pusher/signature.rb:27
Pusher::Signature::Request::ISO8601 = T.let(T.unsafe(nil), String)

# pkg:gem/pusher-signature#lib/pusher/signature.rb:9
class Pusher::Signature::Token
  # pkg:gem/pusher-signature#lib/pusher/signature.rb:12
  def initialize(key, secret); end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:10
  def key; end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:10
  def secret; end

  # pkg:gem/pusher-signature#lib/pusher/signature.rb:16
  def sign(request); end
end
