# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `scrypt` gem.
# Please instead update this file by running `bin/tapioca gem scrypt`.


# NOTE:: a verbatim copy of https://github.com/rails/rails/blob/c8c660002f4b0e9606de96325f20b95248b6ff2d/activesupport/lib/active_support/security_utils.rb
# Please see the Rails license: https://github.com/rails/rails/blob/master/activesupport/MIT-LICENSE
#
# pkg:gem/scrypt#lib/scrypt/errors.rb:3
module SCrypt; end

# pkg:gem/scrypt#lib/scrypt/engine.rb:20
class SCrypt::Engine
  class << self
    # Autodetects the cost from the salt string.
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:145
    def autodetect_cost(salt); end

    # Returns the cost value which will result in computation limits less than the given options.
    #
    # Options:
    # <tt>:max_time</tt> specifies the maximum number of seconds the computation should take.
    # <tt>:max_mem</tt> specifies the maximum number of bytes the computation should take.
    # A value of 0 specifies no upper limit. The minimum is always 1 MB.
    # <tt>:max_memfrac</tt> specifies the maximum memory in a fraction of available resources to use.
    # Any value equal to 0 or greater than 0.5 will result in 0.5 being used.
    #
    # Example:
    #
    #   # should take less than 200ms
    #   SCrypt::Engine.calibrate(:max_time => 0.2)
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:127
    def calibrate(options = T.unsafe(nil)); end

    # Calls SCrypt::Engine.calibrate and saves the cost string for future calls to
    # SCrypt::Engine.generate_salt.
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:134
    def calibrate!(options = T.unsafe(nil)); end

    # pkg:gem/scrypt#lib/scrypt/engine.rb:43
    def calibrated_cost; end

    # pkg:gem/scrypt#lib/scrypt/engine.rb:43
    def calibrated_cost=(_arg0); end

    # Generates a random salt with a given computational cost.  Uses a saved
    # cost if SCrypt::Engine.calibrate! has been called.
    #
    # Options:
    # <tt>:cost</tt> is a cost string returned by SCrypt::Engine.calibrate
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:89
    def generate_salt(options = T.unsafe(nil)); end

    # Given a secret and a valid salt (see SCrypt::Engine.generate_salt) calculates an scrypt password hash.
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:70
    def hash_secret(secret, salt, key_len = T.unsafe(nil)); end

    # Computes the memory use of the given +cost+
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:139
    def memory_use(cost); end

    # pkg:gem/scrypt#lib/scrypt/engine.rb:53
    def scrypt(secret, salt, *args); end

    # Returns true if +cost+ is a valid cost, false if not.
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:99
    def valid_cost?(cost); end

    # Returns true if +salt+ is a valid salt, false if not.
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:104
    def valid_salt?(salt); end

    # Returns true if +secret+ is a valid secret, false if not.
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:109
    def valid_secret?(secret); end

    private

    # pkg:gem/scrypt#lib/scrypt/engine.rb:188
    def __sc_calibrate(max_mem, max_memfrac, max_time); end

    # pkg:gem/scrypt#lib/scrypt/engine.rb:201
    def __sc_crypt(secret, salt, cpu_cost, memory_cost, parallelization, key_len); end

    # Avoids collision with old-style hash detection
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:174
    def avoid_old_style_collision(salt); end

    # Extracts the salt portion from a salt string
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:152
    def extract_salt_from_string(salt); end

    # Generates new-style hash
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:167
    def generate_new_style_hash(secret, salt, salt_only, cost, key_len); end

    # Generates old-style hash with SHA1
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:162
    def generate_old_style_hash(secret, salt, cost); end

    # Checks if this is an old-style hash based on salt length
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:157
    def old_style_hash?(salt_only); end

    # Parses a cost string into its component values
    #
    # pkg:gem/scrypt#lib/scrypt/engine.rb:184
    def parse_cost_string(cost_string); end
  end
end

# Regular expressions for validation
#
# pkg:gem/scrypt#lib/scrypt/engine.rb:22
SCrypt::Engine::COST_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/scrypt#lib/scrypt/engine.rb:46
class SCrypt::Engine::Calibration < ::FFI::Struct; end

# pkg:gem/scrypt#lib/scrypt/engine.rb:30
SCrypt::Engine::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/scrypt#lib/scrypt/engine.rb:24
SCrypt::Engine::HASH_PATTERN = T.let(T.unsafe(nil), Regexp)

# Constants for salt handling
#
# pkg:gem/scrypt#lib/scrypt/engine.rb:27
SCrypt::Engine::OLD_STYLE_SALT_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/scrypt#lib/scrypt/engine.rb:28
SCrypt::Engine::SALT_MIN_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/scrypt#lib/scrypt/engine.rb:23
SCrypt::Engine::SALT_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/scrypt#lib/scrypt/errors.rb:4
module SCrypt::Errors; end

# The hash parameter provided is invalid.
#
# pkg:gem/scrypt#lib/scrypt/errors.rb:9
class SCrypt::Errors::InvalidHash < ::StandardError; end

# The salt parameter provided is invalid.
#
# pkg:gem/scrypt#lib/scrypt/errors.rb:6
class SCrypt::Errors::InvalidSalt < ::StandardError; end

# The secret parameter provided is invalid.
#
# pkg:gem/scrypt#lib/scrypt/errors.rb:12
class SCrypt::Errors::InvalidSecret < ::StandardError; end

# pkg:gem/scrypt#lib/scrypt/scrypt_ext.rb:7
module SCrypt::Ext
  extend ::FFI::Library

  # pkg:gem/scrypt#lib/scrypt/engine.rb:14
  def crypto_scrypt(*_arg0); end

  # pkg:gem/scrypt#lib/scrypt/engine.rb:9
  def sc_calibrate(*_arg0); end

  class << self
    # pkg:gem/scrypt#lib/scrypt/engine.rb:14
    def crypto_scrypt(*_arg0); end

    # pkg:gem/scrypt#lib/scrypt/engine.rb:9
    def sc_calibrate(*_arg0); end
  end
end

# A password management class which allows you to safely store users' passwords and compare them.
#
# Example usage:
#
#   include "scrypt"
#
#   # hash a user's password
#   @password = Password.create("my grand secret")
#   @password #=> "2000$8$1$f5f2fa5fe5484a7091f1299768fbe92b5a7fbc77$6a385f22c54d92c314b71a4fd5ef33967c93d679"
#
#   # store it safely
#   @user.update_attribute(:password, @password)
#
#   # read it back
#   @user.reload!
#   @db_password = Password.new(@user.password)
#
#   # compare it after retrieval
#   @db_password == "my grand secret" #=> true
#   @db_password == "a paltry guess"  #=> false
#
# pkg:gem/scrypt#lib/scrypt/password.rb:25
class SCrypt::Password < ::String
  # Initializes a SCrypt::Password instance with the data from a stored hash.
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:96
  def initialize(raw_hash); end

  # Compares a potential secret against the hash. Returns true if the secret is the original secret, false otherwise.
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:105
  def ==(other); end

  # The cost factor used to create the hash.
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:38
  def cost; end

  # The hash portion of the stored password hash.
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:34
  def digest; end

  # pkg:gem/scrypt#lib/scrypt/password.rb:108
  def is_password?(other); end

  # The salt of the store password hash
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:36
  def salt; end

  private

  # call-seq:
  #   split_hash(raw_hash) -> cost, salt, hash
  #
  # Splits +h+ into cost, salt, and hash and returns them in that order.
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:121
  def split_hash(hash_string); end

  # Returns true if +h+ is a valid hash.
  #
  # pkg:gem/scrypt#lib/scrypt/password.rb:113
  def valid_hash?(h); end

  class << self
    # Hashes a secret, returning a SCrypt::Password instance.
    # Takes five options (optional), which will determine the salt/key's length and
    # the cost limits of the computation.
    # <tt>:key_len</tt> specifies the length in bytes of the key you want to generate.
    # The default is 32 bytes (256 bits). Minimum is 16 bytes (128 bits). Maximum is 512 bytes (4096 bits).
    # <tt>:salt_size</tt> specifies the size in bytes of the random salt you want to generate.
    # The default and minimum is 8 bytes (64 bits). Maximum is 32 bytes (256 bits).
    # <tt>:max_time</tt> specifies the maximum number of seconds the computation should take.
    # <tt>:max_mem</tt> specifies the maximum number of bytes the computation should take.
    # A value of 0 specifies no upper limit. The minimum is always 1 MB.
    # <tt>:max_memfrac</tt> specifies the maximum memory in a fraction of available resources to use.
    # Any value equal to 0 or greater than 0.5 will result in 0.5 being used.
    # The scrypt key derivation function is designed to be far more secure against hardware
    # brute-force attacks than alternative functions such as PBKDF2 or bcrypt.
    # The designers of scrypt estimate that on modern (2009) hardware, if 5 seconds are spent
    # computing a derived key, the cost of a hardware brute-force attack against scrypt is roughly
    # 4000 times greater than the cost of a similar attack against bcrypt (to find the same password),
    # and 20000 times greater than a similar attack against PBKDF2.
    # Default options will result in calculation time of approx. 200 ms with 1 MB memory use.
    #
    # Example:
    #   @password = SCrypt::Password.create("my secret", :max_time => 0.25)
    #
    # pkg:gem/scrypt#lib/scrypt/password.rb:64
    def create(secret, options = T.unsafe(nil)); end

    private

    # Clamps key length to valid range
    #
    # pkg:gem/scrypt#lib/scrypt/password.rb:79
    def clamp_key_length(key_len); end

    # Clamps salt size to valid range
    #
    # pkg:gem/scrypt#lib/scrypt/password.rb:87
    def clamp_salt_size(salt_size); end
  end
end

# pkg:gem/scrypt#lib/scrypt/password.rb:28
SCrypt::Password::MAX_KEY_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/scrypt#lib/scrypt/password.rb:31
SCrypt::Password::MAX_SALT_SIZE = T.let(T.unsafe(nil), Integer)

# Key length constraints
#
# pkg:gem/scrypt#lib/scrypt/password.rb:27
SCrypt::Password::MIN_KEY_LENGTH = T.let(T.unsafe(nil), Integer)

# Salt size constraints
#
# pkg:gem/scrypt#lib/scrypt/password.rb:30
SCrypt::Password::MIN_SALT_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/scrypt#lib/scrypt/security_utils.rb:7
module SCrypt::SecurityUtils
  class << self
    # Constant time string comparison.
    #
    # The values compared should be of fixed length, such as strings
    # that have already been processed by HMAC. This should not be used
    # on variable length plaintext strings because it could leak length info
    # via timing attacks.
    #
    # pkg:gem/scrypt#lib/scrypt/security_utils.rb:14
    def secure_compare(a, b); end
  end
end
