# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LetterOpenerWeb::Engine::GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl LetterOpenerWeb::Engine::GeneratedUrlHelpersModule`.


module LetterOpenerWeb::Engine::GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def clear_letters_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def delete_letter_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def letter_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def letters_url(*args); end
end
