# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_admin_users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_bills_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_comment_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_comments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_common_house_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_common_house_reservations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_communities_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_community_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_dashboard_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_events_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_guest_room_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_guest_room_reservations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_ledger_check_run_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_ledger_check_runs_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_logout_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meal_meal_resident_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meal_meal_residents_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meal_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meals_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_reconciliation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_reconciliations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_resident_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_residents_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_rotation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_rotations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_unit_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_units_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_user_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_user_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_common_house_reservations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_community_ical_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_events_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_guest_room_reservations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_meals_next_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_reconciliations_preview_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_reconciliations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_resident_ical_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_residents_id_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_residents_password_reset_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_residents_token_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_sessions_current_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_version_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def destroy_admin_user_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_common_house_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_community_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_guest_room_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_meal_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_resident_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_unit_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_user_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def letter_opener_web_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_common_house_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_community_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_guest_room_reservation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_meal_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_reconciliation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_resident_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_unit_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_user_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_user_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def schedule_preview_admin_communities_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_password_reset_admin_resident_url(*args); end
end
