# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.


module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_admin_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_bill_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_bills_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_comment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_comments_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_common_house_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_common_house_reservations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_communities_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_community_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_dashboard_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_guest_room_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_guest_room_reservations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_ledger_check_run_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_ledger_check_runs_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meal_meal_resident_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meal_meal_residents_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meal_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_meals_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_reconciliation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_reconciliations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_resident_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_residents_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_rotation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_rotations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_unit_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_units_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_common_house_reservations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_community_ical_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_guest_room_reservations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_meals_next_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_reconciliations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_reconciliations_preview_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_resident_ical_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_residents_id_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_residents_password_reset_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_residents_token_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_sessions_current_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_version_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def destroy_admin_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_bill_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_common_house_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_community_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_guest_room_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_meal_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_resident_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_unit_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def letter_opener_web_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_bill_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_common_house_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_community_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_guest_room_reservation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_meal_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_reconciliation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_resident_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_unit_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def schedule_preview_admin_communities_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def send_password_reset_admin_resident_path(*args); end
end
