# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RecurringJob`.
# Please instead update this file by running `bin/tapioca dsl RecurringJob`.


class RecurringJob
  class << self
    sig { params(block: T.nilable(T.proc.params(job: RecurringJob).void)).returns(T.any(RecurringJob, FalseClass)) }
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
