# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LetterOpenerWeb::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl LetterOpenerWeb::ApplicationController`.


class LetterOpenerWeb::ApplicationController
  include GeneratedMountedHelpers
  include LetterOpenerWeb::Engine::GeneratedUrlHelpersModule
  include LetterOpenerWeb::Engine::GeneratedPathHelpersModule
end
