/**
 * Shared setup helpers for integration tests (real Rails backend).
 *
 * Unlike the mocked E2E setup (setup.js), this helper does NOT mock API routes.
 * All requests hit the real Rails test server. Authentication uses real tokens
 * from the seeded test database.
 */

const fs = require("fs");
const path = require("path");
const { disableIdleTimer, clearStorage } = require("./browser_setup");

// The suite's frozen "today" — bin/test-integration exports it to the
// seed task and the Rails server; the browser freezes to the same
// instant in setupAuthenticatedPage. Noon avoids day-boundary edges.
const FAKE_TODAY = process.env.INTEGRATION_FAKE_TODAY || "2026-01-15";
const FAKE_NOW = new Date(`${FAKE_TODAY}T12:00:00`);

/**
 * Read auth credentials written by `rake test:seed_integration`.
 */
function loadAuthInfo() {
  const authPath = path.resolve(__dirname, "../../tmp/integration_auth.json");
  return JSON.parse(fs.readFileSync(authPath, "utf-8"));
}

/**
 * Set auth cookies from the seeded test data so the app treats the user
 * as logged in. Uses the real token generated by the Rails seed task.
 */
async function authenticateContext(context) {
  const auth = loadAuthInfo();
  await context.addCookies([
    { name: "token", value: auth.token, domain: "localhost", path: "/" },
    {
      name: "community_id",
      value: String(auth.community_id),
      domain: "localhost",
      path: "/",
    },
    {
      name: "resident_id",
      value: String(auth.resident_id),
      domain: "localhost",
      path: "/",
    },
    {
      name: "username",
      value: auth.username,
      domain: "localhost",
      path: "/",
    },
  ]);
}

/**
 * Stub Pusher globally so the app never makes real WebSocket connections.
 * Even with a real backend, we don't want WebSocket flakiness in tests.
 */
async function stubPusher(page) {
  await page.addInitScript(() => {
    window.Pusher = function () {
      this.connection = {
        socket_id: "test-socket-id",
        bind: function () {},
      };
      this.subscribe = function () {
        return {
          bind: function () {},
          unbind_all: function () {},
        };
      };
      this.unsubscribe = function () {};
    };
  });
}

/**
 * Freeze the browser's Date to the suite's fake "today", matching the
 * frozen Rails server. setFixedTime pins Date/Date.now but leaves
 * timers real, so debounce-driven saves still run.
 */
async function freezeClock(page) {
  await page.clock.setFixedTime(FAKE_NOW);
}

/**
 * Full authenticated setup for integration tests.
 * Sets cookies, stubs Pusher, disables idle timer, freezes the clock
 * to the seeded "today". NO API mocking.
 */
async function setupAuthenticatedPage(page, context) {
  await authenticateContext(context);
  await stubPusher(page);
  await disableIdleTimer(page);
  await freezeClock(page);
}

// The meal page fills from GET /cooks after it mounts. A test that
// clicks or types before that answer arrives races the load: the
// arriving data overwrites what it did. So every goto and reload of a
// meal page waits for that GET.
function mealLoaded(page, mealId) {
  return page.waitForResponse(
    (r) =>
      r.request().method() === "GET" &&
      r.url().includes(`/api/v1/meals/${mealId}/cooks`) &&
      r.ok(),
  );
}

async function gotoMeal(page, mealId) {
  const loaded = mealLoaded(page, mealId);
  await page.goto(`/meals/${mealId}/edit/`);
  await loaded;
}

/**
 * Reload a meal page so it can show only what the server has: empty
 * the app's IndexedDB copy first (the page draws that copy before the
 * server answers), then wait for the fresh GET.
 */
async function reloadMeal(page, mealId) {
  await clearStorage(page);
  const loaded = mealLoaded(page, mealId);
  await page.reload();
  await loaded;
}

/**
 * Wait for a successful write to one of this meal's endpoints, for
 * example mealWritten(page, 7, "POST", "residents"). Start the wait
 * before the click, and await it before a reload: a reload that
 * cancels the request makes WebKit log a console error, which the
 * strict fixture in tests/helpers/test.js fails.
 */
function mealWritten(page, mealId, method, pathPart) {
  return page.waitForResponse(
    (r) =>
      r.request().method() === method &&
      r.url().includes(`/api/v1/meals/${mealId}/${pathPart}`) &&
      r.ok(),
  );
}

module.exports = {
  FAKE_TODAY,
  FAKE_NOW,
  loadAuthInfo,
  authenticateContext,
  stubPusher,
  disableIdleTimer,
  clearStorage,
  setupAuthenticatedPage,
  mealLoaded,
  gotoMeal,
  reloadMeal,
  mealWritten,
};
