/**
 * Shared setup helpers for integration tests (real Rails backend).
 *
 * Unlike the mocked E2E setup (setup.js), this helper does NOT mock API routes.
 * All requests hit the real Rails test server. Authentication uses real tokens
 * from the seeded test database.
 */

const fs = require("fs");
const path = require("path");

/**
 * Read auth credentials written by `rake test:seed_integration`.
 */
function loadAuthInfo() {
  const authPath = path.resolve(__dirname, "../../tmp/integration_auth.json");
  return JSON.parse(fs.readFileSync(authPath, "utf-8"));
}

/**
 * Set auth cookies from the seeded test data so the app treats the user
 * as logged in. Uses the real token generated by the Rails seed task.
 */
async function authenticateContext(context) {
  const auth = loadAuthInfo();
  await context.addCookies([
    { name: "token", value: auth.token, domain: "localhost", path: "/" },
    {
      name: "community_id",
      value: String(auth.community_id),
      domain: "localhost",
      path: "/",
    },
    {
      name: "resident_id",
      value: String(auth.resident_id),
      domain: "localhost",
      path: "/",
    },
    {
      name: "username",
      value: auth.username,
      domain: "localhost",
      path: "/",
    },
  ]);
}

/**
 * Stub Pusher globally so the app never makes real WebSocket connections.
 * Even with a real backend, we don't want WebSocket flakiness in tests.
 */
async function stubPusher(page) {
  await page.addInitScript(() => {
    window.Pusher = function () {
      this.connection = {
        socket_id: "test-socket-id",
        bind: function () {},
      };
      this.subscribe = function () {
        return {
          bind: function () {},
          unbind_all: function () {},
        };
      };
      this.unsubscribe = function () {};
    };
  });
}

/**
 * Disable the idle timer that redirects after 5 minutes of inactivity.
 */
async function disableIdleTimer(page) {
  await page.addInitScript(() => {
    window.idleTimer = function () {};
  });
}

/**
 * Clear localforage/IndexedDB to prevent stale cached data between tests.
 */
async function clearStorage(page) {
  await page.evaluate(async () => {
    if (window.localforage) {
      await window.localforage.clear();
    }
    sessionStorage.clear();
  });
}

/**
 * Full authenticated setup for integration tests.
 * Sets cookies, stubs Pusher, disables idle timer. NO API mocking.
 */
async function setupAuthenticatedPage(page, context) {
  await authenticateContext(context);
  await stubPusher(page);
  await disableIdleTimer(page);
}

module.exports = {
  loadAuthInfo,
  authenticateContext,
  stubPusher,
  disableIdleTimer,
  clearStorage,
  setupAuthenticatedPage,
};
